- src/components/FlowCompletion.tsx
- src/components/GoalCreateForm.tsx
- src/components/GoalCreateModal.tsx
- src/components/ProjectCompletion.tsx
- src/components/ProjectCreateForm.tsx
- src/components/ProjectCreateModal.tsx
- src/components/StateDropdown.tsx
- src/components/UserCompletion.tsx
- src/components/UserInviteForm.tsx
- src/components/UserInviteModal.tsx
- src/pages/_app.tsx
- src/pages/goals/new.tsx
- src/pages/projects/new.tsx
- src/pages/users/invite.tsx
> Components naming guide 

- .haskyrc.json
- .husky/pre-commit
- package.json
> Husky must work 

- src/utils/auth.ts
> Create Activity for the new User after OAuth signup 

- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
- graphql/schema.graphql
- graphql/types.ts
- prisma/migrations/20220511165407_/migration.sql
- prisma/schema.prisma
- src/components/ProjectCreateForm.tsx
- src/components/ProjectKeyInput.tsx
- src/hooks/router.ts
- src/pages/goals/[id].tsx
- src/pages/projects/[slug].tsx
- src/utils/keyPredictor.ts
> Project must have uniq key 

- src/utils/dateTime.ts
> Relative date formatter

- src/components/GoalCreateForm.tsx
Add useEffect for passing default goal state when project is changed
Resolve #29
> Default state for Goal must be provided automatically

- prisma/migrations/20220524150010_/migration.sql
- prisma/schema.prisma
Resolve #58
Currently with default value instead of seed script updating.
> State must have color field

- package-lock.json
- package.json
> Fix storybook build

- src/components/DialogPage.tsx
- src/components/EstimateDropdown.tsx
- src/components/FormActions.tsx
- src/components/GoalCreateForm.tsx
- src/components/Header.tsx
- src/components/HeaderLogo.tsx
- src/components/ProjectCreateForm.tsx
- src/components/TagCompletion.tsx
- src/components/UserCompletion.tsx
- src/components/UserInviteForm.tsx
- src/components/UserPic.tsx
- src/pages/goals/new.tsx
- src/pages/index.tsx
- src/pages/projects/new.tsx
> Replace Geist UI: Grid

- graphql/resolvers/Project.ts
- graphql/schema.graphql
- graphql/types.ts
- package-lock.json
- package.json
- prisma/schema.prisma
- src/components/ProjectCreateForm.tsx
- src/components/ProjectCreateModal.tsx
- src/pages/projects/[key].tsx
- src/pages/projects/new.tsx
> Use project key in query string instead of slug 

- .storybook/preview.js
- graphql/types.ts
- prisma/migrations/20220601180838_/migration.sql
- prisma/migrations/20220601185900_/migration.sql
- prisma/schema.prisma
- src/components/State.tsx
- src/pages/_app.tsx
- src/stories/State.stories.tsx
- src/utils/pageContext.ts
> State component 

- graphql/schema.graphql
- src/components/State.tsx
- src/components/StateDot.tsx
- src/stories/StateDot.stories.tsx
> StateDot component

- src/components/GlobalStyle.ts
- src/components/Text.tsx
> Fix text color on light theme

- docker-compose.yml
> Include MailDev into Docker composition with pg

- src/components/Page.tsx
- src/pages/_app.tsx
> Modal doesn't hidden on redirected page after Project/Goal created

- graphql/resolvers/Goal.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- prisma/migrations/20220609190907_/migration.sql
- prisma/schema.prisma
- src/components/Button.tsx
- src/components/Card.tsx
- src/components/EstimateDropdown.tsx
- src/components/GoalCreateModal.tsx
- src/hooks/useMounted.ts
- src/pages/goals/[id].tsx
- src/utils/nullable.ts
> Goal: add estimate button

- graphql/resolvers/Goal.ts
- graphql/schema.graphql
- graphql/types.ts
- prisma/migrations/20220609220740_/migration.sql
- prisma/migrations/20220609224307_/migration.sql
- prisma/schema.prisma
- src/components/EstimateDropdown.tsx
- src/components/Icon.tsx
- src/pages/goals/[id].tsx
- src/utils/auth.ts
> Goal: add follow/unfollow button 

- i18n/en.json
- i18n/ru.json
- src/components/Button.tsx
- src/components/Card.tsx
- src/components/EstimateDropdown.tsx
- src/components/FlowCompletion.tsx
- src/components/Icon.tsx
- src/components/Input.tsx
- src/components/ProjectCompletion.tsx
- src/components/ProjectKeyInput.tsx
- src/components/StateDropdown.tsx
- src/components/TagCompletion.tsx
- src/components/UserCompletion.tsx
- src/components/UserInviteForm.tsx
- src/pages/goals/[id].tsx
- src/stories/Input.stories.tsx
> Replace Geist UI: Input

- src/components/EstimateDropdown.tsx
- src/components/FlowCompletion.tsx
- src/components/Form.tsx
- src/components/ProjectCompletion.tsx
- src/components/ProjectKeyInput.tsx
- src/components/StateDropdown.tsx
- src/components/TagCompletion.tsx
- src/components/UserCompletion.tsx
- src/hooks/useKeyboard.ts
> Replace Geist UI: useKeyboard, KeyCode 

- src/components/Header.tsx
> Header must have own background

- src/hooks/useHotkeys.ts
- src/utils/hotkeys.ts
> Hotkey redirects me when I create a tag ('gg' -> new page)

- src/components/GoalCreateForm.tsx
- src/components/IssueKey.tsx
- src/components/IssueStats.tsx
- src/components/IssueTitle.tsx
- src/components/Modal.tsx
- src/components/Tip.tsx
- src/pages/goals/[id].tsx
- src/pages/users/settings.tsx
> Paddings/margins as an standard 

- i18n/en.json
- i18n/ru.json
- src/components/HotkeysModal.tsx
- src/components/Keyboard.tsx
- src/components/Modal.tsx
- src/components/Page.tsx
- src/components/PageSep.tsx
> Hotkeys helper with h long press

- i18n/en.json
- i18n/ru.json
- src/components/HotkeysModal.tsx
- src/utils/hotkeys.ts
> Fix hotkeys longpress handling

- src/components/Footer.tsx
> Footer paddings, text color and Anny align not as in design #158

- src/components/Form.tsx
> Goal updates with CMD+Enter in time of Modal is opened

- src/components/State.tsx
- src/components/StateSwitch.tsx
- src/pages/goals/[id].tsx
> Goal: switch state

- graphql/resolvers/Goal.ts
> Goal issuer must be goal watcher by default

- graphql/context.ts
- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
- graphql/resolvers/Reaction.ts
- graphql/resolvers/Settings.ts
- graphql/resolvers/Tag.ts
- graphql/resolvers/User.ts
- graphql/schema.graphql
- graphql/schema.ts
- graphql/types.ts
- package-lock.json
- package.json
- prisma/schema.prisma
- src/components/Button.tsx
- src/components/Card.tsx
- src/components/GoalEditForm.tsx
- src/components/Icon.tsx
- src/components/Reactions.tsx
- src/components/ReactionsButton.tsx
- src/components/ReactionsDropdown.tsx
- src/pages/api/graphql.ts
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key].tsx
- src/pages/users/settings.tsx
- src/stories/ReactionsDropdown.stories.tsx
- src/utils/createFetcher.ts
- src/utils/pageContext.ts
> Goal: add reactions control

- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
- graphql/resolvers/Reaction.ts
- graphql/schema.graphql
- graphql/types.ts
- prisma/migrations/20220701134336_/migration.sql
- prisma/schema.prisma
- src/components/GoalCreateForm.tsx
- src/components/ProjectCreateForm.tsx
- src/components/Reactions.tsx
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key].tsx
- src/stories/Goal/GoalItem.stories.tsx
> Activity and activityId everywhere

- graphql/resolvers/Goal.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/GoalCreateForm.tsx
- src/components/GoalEditForm.tsx
- src/components/TagCompletion.tsx
> Tags update for Goal 

- src/components/EstimateDropdown.tsx
- src/components/FlowCompletion.tsx
- src/components/Form.tsx
- src/components/GoalEditModal.tsx
- src/components/IssueDependencyKindDropdown.tsx
- src/components/IssueSearchInput.tsx
- src/components/Modal.tsx
- src/components/ProjectCompletion.tsx
- src/components/ProjectKeyInput.tsx
- src/components/StateDropdown.tsx
- src/components/StateSwitch.tsx
- src/components/TagCompletion.tsx
- src/components/UserCompletionDropdown.tsx
- src/components/UserCompletionInput.tsx
- src/hooks/useKeyboard.ts
> Goal updates with Enter press from anywhere on goal page

- src/pages/goals/[id].tsx
> State cached between routes

- src/components/Modal.tsx
> Modal for participants and dependencies edit doesn't close with ESC

- src/utils/auth.ts
> Support KeyCloak provider for next-auth

- package-lock.json
- package.json
- src/components/Md.tsx
- src/components/Text.tsx
- src/utils/md.ts
> MD renderer

- Dockerfile.production
- app_run_production.sh
- src/utils/auth.ts
- src/utils/prisma.ts
> Production setup and Keycloak support

- graphql/resolvers/Comment.ts
- src/utils/mailServer.ts
> Unlock email notifications for comments (debug)

- src/hooks/useUpload.ts
- src/pages/api/upload.ts
Resolve #247
How to check uploads:
`src/pages/upload.tsx`
``` ts
import React from 'react';
import { declareSsrProps, ExternalPageProps } from '../utils/declareSsrProps';
import { Page } from '../components/Page';
import { useUpload } from '../hooks/useUpload';
export const getServerSideProps = declareSsrProps();
const UploadPage = ({ locale }: ExternalPageProps) => {
const { loading, files, onFileInputChange } = useUpload();
return (
<Page locale={locale} title={'test'}>
<input onChange={onFileInputChange} type="file" multiple />
<div>{loading ? 'loading...' : null}</div>
<div>
{files?.map((file, index) => (
<div key={index}>
File #{index}: {file}
</div>
))}
</div>
</Page>
);
};
export default UploadPage;
```
> useUpload hook

- src/components/GoalCreateForm.tsx
- src/components/GoalEditForm.tsx
> GoalCreateForm, GoalEditForm: Impossible to remove tag 

- src/components/GoalForm.tsx
> Limit Goal tags with 5

- src/pages/api/upload.ts
> Allow only authenticated users to read from aws bucket

- src/components/Comment.tsx
- src/components/CommentCreateForm.tsx
- src/components/HeaderMenu.tsx
- src/components/UserPic.tsx
- src/pages/goals/[id].tsx
> Same avatar image everywhere 

- src/components/FormInput.tsx
- src/components/FormTextarea.tsx
> FormInput: hover style, description 

- graphql/resolvers/Project.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- src/components/FiltersMenuItem.tsx
- src/components/GoalItem.tsx
- src/components/Page.tsx
- src/components/StateDropdownItem.tsx
- src/components/StateFilter.tsx
- src/pages/projects/[key].tsx
> Add filters and search to goals page 

- src/components/Card.tsx
- src/components/Comment.tsx
> Comment card height must be same with lines of comment

- graphql/resolvers/Comment.ts
- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
- graphql/resolvers/User.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/GoalCreateForm.tsx
- src/components/GoalEditForm.tsx
- src/components/GoalForm.tsx
- src/components/GoalItem.tsx
- src/components/IssueParticipantsForm.tsx
- src/components/ProjectCreateForm.tsx
- src/components/ProjectItem.tsx
- src/components/UserCompletionDropdown.tsx
- src/components/UserCompletionInput.tsx
- src/components/UserDropdownItem.tsx
- src/pages/explore/projects.tsx
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
- src/pages/projects/[key]/settings.tsx
- src/stories/GoalItem.stories.tsx
> Remove magic with computed fields 

- src/components/FiltersPanel.tsx
- src/components/StateFilter.tsx
- src/pages/projects/[key]/index.tsx
> Save filter in query string

- src/pages/projects/[key]/index.tsx
> "Load more" button is visible, but should not

- src/components/HeaderMenu.tsx
> После разлогинивания невозможно снова залогиниться

- package-lock.json
- package.json
- src/utils/keyPredictor.ts
> Improve project key generator

- src/components/HeaderMenu.tsx
https://github.com/taskany-inc/issues/commit/0c0c3b07b7b966d90cd10d759a20cbd075ac1454
> Fix UserPic in HeaderMenu

- graphql/resolvers/Goal.ts
> Goal id must starts from zero in every new project

- graphql/resolvers/Comment.ts
- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
- graphql/resolvers/Reaction.ts
- graphql/resolvers/Settings.ts
- graphql/resolvers/User.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/GoalEditForm.tsx
- src/components/IssueDependenciesForm.tsx
- src/components/ProjectStarButton.tsx
- src/components/ProjectWatchButton.tsx
- src/pages/goals/[id].tsx
> Same signature for create resolvers with inputObjectType

- i18n/en.json
- i18n/ru.json
- src/components/FiltersPanel.tsx
- src/components/GoalCreateForm.tsx
- src/components/ModalOnEvent.tsx
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
- src/utils/dispatchModal.ts
> Pass dependency kind with ModalEvent to editing form and preselect this dependency kind

- graphql/resolvers/Goal.ts
- src/components/FormEditor.tsx
- src/components/Modal.tsx
- src/components/ModalOnEvent.tsx
- src/pages/goals/[id].tsx
> Close GoalEditModal after save

- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- prisma/migrations/20221030202121_/migration.sql
- prisma/schema.prisma
- src/components/GoalCreateForm.tsx
- src/components/GoalEditForm.tsx
- src/components/GoalForm.tsx
- src/components/PriorityDropdown.tsx
- src/components/StateDropdown.tsx
- src/pages/goals/[id].tsx
- src/pages/projects/[key]/index.tsx
> Add priority field to goals

- .husky/pre-push
- .lintstagedrc
- package.json
> Reanimate husky

- package-lock.json
- package.json
- src/utils/dateTime.test.ts
- src/utils/dateTime.ts
> Replace date-fns with Intl

- graphql/resolvers/Goal.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/CommentView.tsx
- src/components/Reactions.tsx
- src/components/ReactionsDropdown.tsx
- src/pages/goals/[id].tsx
> Reactions for comments

- .husky/pre-commit
> Run all binaries in scripts with npx

- graphql/resolvers/Comment.ts
> Do not send email if comment and goal author are same

- src/components/EstimateDropdown.tsx
- src/components/GoalCreateForm.tsx
- src/components/GoalEditForm.tsx
- src/components/GoalForm.tsx
- src/pages/goals/[id].tsx
- src/utils/dateTime.test.ts
- src/utils/dateTime.ts
> Fail with dateTime parsing in EstimateDropdown

- graphql/resolvers/Goal.ts
> Goal comments must be sorted via createdAt field

- src/pages/goals/[id].tsx
- src/pages/projects/[key]/index.tsx
- src/pages/projects/[key]/settings.tsx
- src/utils/dateTime.ts
- src/utils/declareSsrProps.ts
> Check all private routes. No runtime errors, just redirect to auth page.

- graphql/resolvers/User.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/IssueParticipantsForm.tsx
- src/components/IssueParticipantsList.tsx
- src/components/UserCompletionDropdown.tsx
- src/components/UserCompletionInput.tsx
> Filter participants from autocomplete in IssueParticipantsForm

- src/components/FiltersPanel.tsx
- src/components/LimitFilter.tsx
- src/components/StateFilter.tsx
- src/components/TagsFilter.tsx
- src/components/UserFilter.tsx
- src/hooks/useUrlParams.ts
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
> Support all available filters via URL

- graphql/resolvers/Comment.ts
> Send emails if recipients exists

- src/components/CommentCreateForm.tsx
- src/components/Form.tsx
- src/components/GoalForm.tsx
- src/components/ProjectCreateForm.tsx
- src/utils/hotkeys.ts
Действительно таким образом работает Resolve #323
> Project/Goal/Comment creation doesn't work via CMD + Enter

- src/components/CommentView.tsx
> Any user can edit any comment

- src/components/Gravatar.tsx
- src/components/UserPic.tsx
> Fallback UserPic on 404 to default avatar

- src/components/FormEditor.tsx
- src/components/FormInput.tsx
- src/components/GoalForm.tsx
> Support errors for FormEditor

- graphql/resolvers/Goal.ts
> Invalid prisma.goal.create() invocation: Unique constraint failed on the fields: (id)

- src/components/ComboBox.tsx
- src/components/Dropdown.tsx
- src/components/IssueDependenciesForm.tsx
- src/components/Popup.tsx
- src/stories/ComboBox.stories.tsx
> Support errors for Dropdown and ComboBox

- package-lock.json
- package.json
- prisma/seed.ts
> Seed db with full data for demo and local development

- graphql/resolvers/Goal.ts
- graphql/schema.graphql
- graphql/types.ts
- prisma/seed.ts
- src/components/ColorizedMenuItem.tsx
- src/components/GoalForm.tsx
- src/components/PriorityDropdown.tsx
- src/components/StateDropdown.tsx
- src/components/StateFilterDropdown.tsx
- src/pages/goals/[id].tsx
> Make priority field much more attractive

- i18n/en.json
- i18n/ru.json
- src/components/ProjectCreateForm.tsx
> Danger color flapping in ProjectKeyInput

- src/components/Button.tsx
- src/components/GlobalStyle.ts
- src/components/GoalForm.tsx
- src/components/GoalListItem.tsx
- src/components/GoalPreview.tsx
- src/components/IssueDependenciesForm.tsx
- src/components/IssueProject.tsx
- src/components/IssueStats.tsx
- src/components/IssueTags.tsx
- src/components/IssueTitle.tsx
- src/components/Modal.tsx
- src/components/ModalOnEvent.tsx
- src/components/ModalPreview.tsx
- src/components/Popup.tsx
- src/components/ProjectCreateForm.tsx
- src/components/Text.tsx
- src/components/UserInviteForm.tsx
- src/hooks/useGoalUpdate.ts
- src/hooks/useHighlightedComment.ts
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
- src/pages/projects/[key]/settings.tsx
- src/utils/entityFetcher.ts
> Хочется иметь окно-превью справа

- src/pages/goals/index.tsx
> Header jumping in GoalPreview

- src/components/Md.tsx
> Oversized images in comments 

- src/components/GoalPreview.tsx
- src/components/IssueTitle.tsx
> Goal title in GoalPreview must be highlighted on hover

- src/components/GoalPreview.tsx
- src/components/IssueProject.tsx
> IssueStats line break in GoalPreview 

- src/components/GoalPreview.tsx
> Oversized header in GoalPreview if title length more than one line

- src/components/Page.tsx
- src/components/State.tsx
- src/pages/explore/projects.tsx
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/help/[locale]/[slug].tsx
- src/pages/index.tsx
- src/pages/projects/[key]/index.tsx
- src/pages/projects/[key]/settings.tsx
- src/pages/users/[id].tsx
- src/pages/users/settings.tsx
- src/utils/auth.ts
- src/utils/pageContext.ts
> StateSwitch flashing 

- src/components/Page.tsx
- src/components/RelativeTime.tsx
- src/hooks/usePageContext.ts
- src/pages/explore/projects.tsx
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/help/[locale]/[slug].tsx
- src/pages/projects/[key]/index.tsx
- src/pages/projects/[key]/settings.tsx
- src/pages/users/[id].tsx
- src/pages/users/settings.tsx
- src/utils/dateTime.ts
- src/utils/declareSsrProps.ts
- src/utils/pageContext.ts
- src/utils/prisma.ts
> Relative time mismatch 

- src/components/Header.tsx
- src/components/State.tsx
- src/components/StateDot.tsx
> Prop href did not match

- graphql/resolvers/Goal.ts
- src/components/GoalCreateForm.tsx
- src/components/ModalOnEvent.tsx
- src/components/ProjectComboBox.tsx
- src/hooks/useLocalStorage.ts
- src/hooks/useWillUnmount.ts
- src/pages/goals/[id].tsx
- src/pages/projects/[key]/index.tsx
- src/types/localStorage.ts
- src/utils/dispatchModal.ts
- src/utils/safelyParseJson.ts
> Predict project for GoalCreateForm

- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
> Add sorting to Goal resolver results

- src/components/GoalCreateForm.tsx
- src/components/ProjectComboBox.tsx
- src/hooks/useLocalStorage.ts
- src/pages/goals/[id].tsx
- src/pages/projects/[key]/index.tsx
- src/types/localStorage.ts
> Types for localStorage keys

- src/components/CommonHeader.tsx
- src/components/FormInput.tsx
- src/components/InputContaier.tsx
- src/components/ProjectCreateForm.tsx
- src/utils/keyPredictor.ts
> FormInput width for the long text and absolute key control

- i18n/ru.json
> No translation for comment actions in ru locale

- graphql/resolvers/Project.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- src/components/Link.tsx
- src/components/ProjectPageLayout.tsx
- src/components/TeamCreateForm.tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
- src/pages/projects/[key]/settings.tsx
> Show teams on project page above project title 

- i18n/en.json
- i18n/ru.json
- src/components/Dropdown.tsx
- src/components/Header.tsx
- src/components/HeaderMenu.tsx
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
- src/pages/teams/[slug]/goals.tsx
- src/pages/users/settings.tsx
> Global Create button

- src/components/CommentView.tsx
> Imposible to select text of comment

- src/components/IssueParticipantsForm.tsx
> Broken goal participants modal layout 

- graphql/resolvers/Team.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- src/components/Page.tsx
- src/components/TeamCreateForm.tsx
- src/pages/teams/[slug]/goals.tsx
> Team may have flow

- graphql/resolvers/Goal.ts
- graphql/schema.graphql
- graphql/types.ts
- prisma/migrations/20230123151736_/migration.sql
- prisma/schema.prisma
- src/components/GoalEditForm.tsx
- src/components/GoalForm.tsx
- src/hooks/useLocalStorage.ts
- src/pages/goals/[id].tsx
- src/pages/projects/[key]/index.tsx
- src/utils/entityFetcher.ts
> Add goal kind field

- src/components/Button.tsx
> Incorrect text color on warning button

- src/components/GoalPreview.tsx
> Reorder important actions on goal page

- next.config.js
> Dashboard is root page

- graphql/resolvers/Goal.ts
- graphql/schema.graphql
- graphql/types.ts
- src/pages/goals/index.tsx
> Show team's goals on dashboard

- graphql/resolvers/Goal.ts
> Move goal btw projects

- graphql/resolvers/Goal.ts
- i18n/en.json
- i18n/ru.json
- src/components/GoalPreview.tsx
- src/components/IssueParent.tsx
- src/pages/goals/[id].tsx
- src/utils/entityFetcher.ts
> Show project teams on goal page

- graphql/resolvers/Project.ts
- graphql/resolvers/Team.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- src/components/ComboBox.tsx
- src/components/FormInput.tsx
- src/components/FormMultiInput.tsx
- src/components/ProjectPageLayout.tsx
- src/hooks/useProjectResource.ts
- src/pages/projects/[key]/settings.tsx
- src/pages/teams/[slug]/settings.tsx
> Set teams for project in settings 

- graphql/resolvers/Goal.ts
- graphql/resolvers/Team.ts
> Include team and project names to search in goals list

- src/hooks/useUrlParams.ts
> Incorrect work with History API in useUrlSearchParams

- src/components/ExplorePageLayout.tsx
- src/components/Gravatar.tsx
- src/components/Header.tsx
> Hide team goals tab on explore page

- src/components/GoalPreview.tsx
- src/components/Modal.tsx
- src/components/ModalPreview.tsx
> Allow goal editing from GoalPreview

- src/components/CommonHeader.tsx
> Multiline project title 

- src/components/IssueListItem.tsx
> Incorrect status view on dependencies 

- graphql/resolvers/Project.ts
- graphql/schema.graphql
- graphql/types.ts
- src/pages/projects/[key]/index.tsx
- src/pages/teams/[slug]/goals.tsx
> No refresh after edits in GoalPreview on project or team page 

- src/pages/goals/index.tsx
> Links to team and project in group title on dashboard 

- src/components/GoalForm.tsx
> Incorrect tags position in GoalCreateForm 

- src/components/IssueParent.tsx
- src/pages/goals/[id].tsx
> Incorrect hierarchy of titles 

- graphql/resolvers/Goal.ts
- graphql/resolvers/Project.ts
- graphql/resolvers/Team.ts
- prisma/migrations/20230218085541_/migration.sql
- prisma/schema.prisma
> Incorrect user goals compilation 

- .gitignore
- package.json
- src/components/GoalPreview.tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
- src/pages/teams/[slug]/goals.tsx
> Crash after goal deleting from GoalPreview 

- src/components/Button.tsx
- src/components/EstimateComboBox.tsx
- src/components/GoalForm.tsx
- src/components/GoalParentComboBox.tsx
- src/components/PriorityDropdown.tsx
- src/components/ReactionsButton.tsx
- src/components/StateDropdown.tsx
- src/components/TagComboBox.tsx
- src/components/UserComboBox.tsx
> При длинном названии проекта кнопка "Создать цель" скрыта

- prisma/seed.ts
- src/components/ProjectPageLayout.tsx
> Incorrect tags seeding 

- prisma/migrations/20230228142135_/migration.sql
- prisma/schema.prisma
> Tag title must be unique 

- src/components/GoalParentComboBox.tsx
> Undefined for some project and teams in GoalCreateForm 

- src/components/CommentCreateForm.tsx
> Incorrect comment publish

- src/components/GoalGroup.tsx
- src/components/GoalListItem.tsx
- src/components/Tag.tsx
- src/components/TagsFilterDropdown.tsx
- src/hooks/useUrlFilterParams.ts
- src/pages/goals/index.tsx
- src/pages/projects/[key]/index.tsx
- src/pages/teams/[slug]/goals.tsx
> Click on Goal tag in GoalListItem adds tag to TagFilter

- graphql/resolvers/Team.ts
- graphql/schema.graphql
- graphql/types.ts
- prisma/migrations/20230304140352_/migration.sql
- prisma/migrations/20230304144029_/migration.sql
- prisma/schema.prisma
- src/components/GoalGroup.tsx
- src/components/IssueParent.tsx
- src/components/ProjectListItem.tsx
- src/components/TeamCreateForm.tsx
- src/components/TeamListItem.tsx
- src/components/TeamPageLayout.tsx
- src/components/TeamTitleList.tsx
- src/hooks/router.ts
- src/pages/explore/projects.tsx
- src/pages/explore/teams.tsx
- src/pages/goals/index.tsx
- src/pages/projects/[key]/settings.tsx
- src/pages/teams/[key]/goals.tsx
- src/pages/teams/[key]/index.tsx
- src/pages/teams/[key]/settings.tsx
- src/utils/entityFetcher.ts
> Слишком длинный урл у команды с длинным названием

- i18n/en.json
- i18n/ru.json
- prisma/migrations/20230304151656_/migration.sql
- prisma/schema.prisma
- src/components/KeyInput.tsx
- src/components/ProjectCreateForm.tsx
- src/components/TeamCreateForm.tsx
- src/pages/projects/[key]/index.tsx
- src/utils/keyPredictor.ts
> Impossible to set custom project key

- src/utils/keyPredictor.ts
> Юникод-символы в названии ломают страницу проекта

- src/components/UserMenuItem.tsx
> Broken images in owner filter 

- src/components/Gravatar.tsx
- src/components/UserPic.tsx
> Broken images in SSR 

- src/utils/prisma.ts
> Impossible to sign in

- prisma/migrations/20230228142135_/migration.sql
- prisma/schema.prisma
This reverts commit f76868fbdaf4acae150e0cec671c2d3949ebdc7a.
> Revert "chore(Tag): title must be unique"

- package-lock.json
- package.json
- src/utils/keyPredictor.test.ts
- src/utils/keyPredictor.ts
> Do we really need slugify?

- package-lock.json
- package.json
> 404 after client redirect from team to project page 

- graphql/resolvers/Reaction.ts
- src/components/Reactions.tsx
> One kind of reaction for one person 

- graphql/resolvers/Project.ts
- graphql/resolvers/Team.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/ProjectPageLayout.tsx
- src/components/UserComboBox.tsx
- src/components/pages/ProjectSettingsPage/ProjectSettingsPage.i18n/en.json
- src/components/pages/ProjectSettingsPage/ProjectSettingsPage.i18n/ru.json
- src/components/pages/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/pages/TeamSettingsPage/TeamSettingsPage.i18n/en.json
- src/components/pages/TeamSettingsPage/TeamSettingsPage.i18n/ru.json
- src/components/pages/TeamSettingsPage/TeamSettingsPage.tsx
- src/hooks/useProjectResource/index.ts
- src/utils/dispatchModal.ts
> Transfer project ownership

- graphql/queries/goals.ts
- graphql/resolvers/Team.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- src/components/CommonHeader.tsx
- src/components/EstimateFilterDropdown.tsx
- src/components/FiltersPanel.tsx
- src/components/pages/GoalsPage/GoalsPage.tsx
- src/components/pages/ProjectPage/ProjectPage.tsx
- src/components/pages/TeamGoalsPage/TeamGoalsPage.tsx
- src/hooks/useUrlFilterParams.ts
> Add estimate filter 

- graphql/queries/goals.ts
- graphql/resolvers/Team.ts
- graphql/schema.graphql
- graphql/types.ts
- i18n/en.json
- i18n/ru.json
- src/components/FiltersPanel.tsx
- src/components/ProjectFilterDropdown.tsx
- src/components/pages/GoalsPage/GoalsPage.tsx
- src/components/pages/ProjectPage/ProjectPage.tsx
- src/components/pages/TeamGoalsPage/TeamGoalsPage.tsx
- src/hooks/useUrlFilterParams.ts
> Projects filter 

- app_run.sh
> Do not migrate when app is starting 

- graphql/resolvers/Project.ts
- graphql/resolvers/Team.ts
- graphql/schema.graphql
- graphql/types.ts
- prisma/migrations/20230405161213_/migration.sql
- prisma/migrations/20230405163310_/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- src/components/FiltersPanel.tsx
- src/components/GoalForm.tsx
- src/components/ProjectCreateForm.tsx
- src/components/ProjectFilterDropdown.tsx
- src/components/pages/TeamSettingsPage/TeamSettingsPage.tsx
- src/hooks/useGrouppedGoals.ts
- src/hooks/useProjectResource/index.ts
- src/hooks/useUrlFilterParams.ts
> Team and Project id is String and not autoincrement

- graphql/types.ts
- prisma/migrations/20230406112202_/migration.sql
- prisma/migrations/20230406121340_/migration.sql
- prisma/schema.prisma
> Prepare Project model for Team implementation 

- prisma/migrations/20230413223931_/migration.sql
- prisma/schema.prisma
> Drop Team table 

- package-lock.json
- package.json
- src/components/ColorizedMenuItem.tsx
- src/components/Page.tsx
- src/components/PriorityDropdown.tsx
- src/components/PriorityFilterDropdown.tsx
- src/components/StateDot.tsx
- src/components/StateDropdown.tsx
- src/components/StateFilterDropdown.tsx
> Bricks: ColorizedMenuItem

- package-lock.json
- package.json
- src/components/Md.tsx
- src/hooks/useMarkdown.ts
> Bricks: Md

- src/components/Page.tsx
> Fix watch button markup

- graphql/resolvers/Filter.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/NotificationsHub/NotificationsHub.i18n/en.json
- src/components/NotificationsHub/NotificationsHub.i18n/ru.json
- src/components/PageTitle.tsx
- src/components/pages/GoalsPage/GoalsPage.tsx
- src/components/pages/ProjectPage/ProjectPage.tsx
- src/hooks/useFilterResource.ts
- src/hooks/useUrlFilterParams.ts
> Only filter owner can delete it 

- graphql/resolvers/Project.ts
- package-lock.json
- package.json
- src/components/FiltersPanel/FiltersPanel.tsx
> FiltersPanel search debounce 

- src/components/IssueDependenciesForm/IssueDependenciesForm.tsx
- src/components/RelativeTime/RelativeTime.tsx
> Hydration errors with other locale

- graphql/resolvers/Goal.ts
> Goal participants are not editable 

- src/components/GoalPreview/GoalPreview.tsx
- src/components/IssueStats/IssueStats.tsx
- src/components/pages/GoalPage/GoalPage.tsx
Resolve #833
https://user-images.githubusercontent.com/982072/234343900-e345bc77-625a-42b7-85fd-802a2b251d30.mov
> GoalPreview isn't scrollable after click on comments anchor 

- graphql/resolvers/Project.ts
- graphql/schema.graphql
- graphql/types.ts
- src/components/ProjectPageLayout/ProjectPageLayout.tsx
- src/components/pages/ProjectPage/ProjectPage.tsx
- src/components/pages/ProjectSettingsPage/ProjectSettingsPage.tsx
> Calc project owner in resolver

- src/components/ProjectPageLayout/ProjectPageLayout.tsx
Resolve #795
- go to project page
- set any filter
- check Goals tab is highlighted
> There are not highlight on TabsMenu after page reload with query params

- src/components/GoalPreview/GoalPreview.tsx
- src/components/pages/GoalsPage/GoalsPage.tsx
- src/components/pages/ProjectPage/ProjectPage.tsx
Resolve #757
- create goal with any diff owner
- login with its account
- try to edit goal from GoalsPage, GoalPage, ProjectPage
> Project owner can edit all goals as goal issuer

- graphql/resolvers/Project.ts
Resolve #850
- go to project page
- try to click on Watch button
> Invalid prisma.activity.update() invocation 

- src/components/GoalPreview/GoalPreview.tsx
Resolve #698
- create goal with long title, like 200+ symbols
- add some long comments
- open goal in preview on any page
- scroll down
- you must see CommentForm
> Unavailable comment form for large content

- src/components/IssueStats/IssueStats.tsx
- src/components/RelativeTime/RelativeTime.tsx
Resolve #745
- go to goal page
- edit goal
- see correct updated time
> Incorrect relative time after editing 

- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
> Conventional commits

- package-lock.json
- package.json
> Conventional Changelog 

- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/pages/ProjectPage/ProjectPage.tsx
Resolve #865
- go to project page
- emit GoalCreateForm
- default state is available
- after adding title and desc submit button is enabled
> Impossible to create goals with suggested project

- src/components/FiltersPanelApplied/FiltersPanelApplied.tsx
Resolve #805
- create filter with some projects
- go to other project page and apply filter
- you don't see empty strings in applied values below filters panel
> Unavailable filter presets for current set

- package-lock.json
> Vulnerabilities audit

- graphql/queries/goals.ts
Resolve #908
- create project
- from diff acc create goal in this project
- from first acc try to edit this goal
> Recursive editing rights 

- .github/workflows/nextjs_bundle_analysis.yml
- package.json
> Use Next.js Bundle Analysis 

- .github/workflows/codeql-analysis.yml
- .github/workflows/nextjs_bundle_analysis.yml
- .github/workflows/pr.yml
- .github/workflows/publish.yml
- Dockerfile.enterprise
- README.md
> Introduce enterprise version 

- package-lock.json
- package.json
> Add dotenv

- next.config.js
- package-lock.json
- package.json
> Correct Sentry plugin usage

- .env.example
- next.config.js
- src/pages/_document.tsx
Resolve #954
No changes in user workflow
> react and react-dom are extermal with include option

- src/components/GoalPage/GoalPage.tsx
- src/components/ProjectPageLayout/ProjectPageLayout.tsx
- src/components/StarButton/StarButton.tsx
- src/components/WatchButton/WatchButton.tsx
- src/hooks/useGoalResource.ts
- src/hooks/useProjectResource.ts
Resolve #948
On any goal or project page click on star or watch buttons is call invalidate page cache and the star counter had correct value
> Stars count doesn't update by Stars button click

- src/components/GoalPage/GoalPage.tsx
Now, in goal dropdown content doesn't wrap by lines
Resolve #716
> Incorrect dropdown width in ru locale

- src/components/FiltersPanelApplied/FiltersPanelApplied.tsx
> Incorrect space position in FiltersPanelApplied

- Dockerfile
- README.md
- src/components/GoalDeleteModal/GoalDeleteModal.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
Resolve #980
Related issues https://github.com/taskany-inc/bricks/issues/101
> UUID to confirm deleting goal

- src/utils/db.ts
Resolve #992
- create new project
- try to create new goal in this project
- it works
> Impossible to create goal in empty project

- src/components/GoalDeleteModal/GoalDeleteModal.tsx
Resolve [#101](https://github.com/taskany-inc/bricks/issues/101)
> FormInput: autoFocus doesn't work

- src/components/FormEditor/FormEditor.i18n/ru.json
Resolve [#951](https://github.com/taskany-inc/issues/issues/951)
> Text under controls in ru locale

- src/schema/goal.ts
Resolve  #999
- create goal w/o estimate
- open edit dialog
- edit any field except estimate
- try to save
- well done
> Impossible to update goal w/o estimate

- trpc/router/project.ts
Resolve #1001 
How to check:
- go to project settings
- select new parent
- try to save
- well done!
> Error on project update with new parent

- src/components/GoalEditForm/GoalEditForm.tsx
- trpc/router/goal.ts
Resolve #1003
Check:
- go to any goal
- open edit dialog
- change project
- try to save
- well done!
> Error on project change in GoalEditForm

- src/components/GoalListItem/GoalListItem.tsx
- src/components/GoalsGroup.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/ProjectPage/ProjectPage.tsx
Resolve #1007 
This fix should help us to keep common with for same cells in different goals groups
> Create a united table for goals groups

- src/components/GoalListItem/GoalListItem.tsx
- src/components/State.tsx
Resolve #1009 
_Please replace this line with instructions on how to test your changes, a note on the devices and browsers this has been tested on, as well as any relevant images for UI changes._
> Change StateDot to State component in GoalsListItem

- src/components/GoalListItem/GoalListItem.tsx
> Bigger paddings for GoalListItem

- src/components/GoalListItem.tsx
- src/components/GoalsGroup.tsx
> Modern grid markup to GoalsGroup

- package-lock.json
- package.json
- src/components/GoalCreateForm/GoalCreateForm.i18n/en.json
- src/components/GoalCreateForm/GoalCreateForm.i18n/ru.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalEditForm/GoalEditForm.tsx
- src/components/GoalForm/GoalForm.tsx
Resolve [#717](https://github.com/taskany-inc/issues/issues/717)
> Create one more goal" checkbox in GoalCreateForm

- package-lock.json
- package.json
> Remove useless semver

- package-lock.json
- package.json
- src/components/CommentView/CommentView.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/RelativeTime/RelativeTime.tsx
Resolve [#413 ](https://github.com/taskany-inc/issues/issues/413)
> Double click on comment bar changes date format

- src/components/KeyInput.tsx
- src/utils/keyPredictor.test.ts
- src/utils/keyPredictor.ts
Resolve [#715](https://github.com/taskany-inc/issues/issues/715)
> Allow vowels for custom project key

- prisma/migrations/20230601105643_/migration.sql
- prisma/schema.prisma
- src/components/EstimateComboBox.tsx
- src/components/GoalEditForm/GoalEditForm.tsx
- src/schema/goal.ts
- src/utils/dateTime.ts
- src/utils/db.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
- trpc/router/project.ts
Here includes two migrations and update script for `estimate` which change `date` value from localized to short iso
Left to do
Resolve #985
> Upsert estimate field instead of create and create history record about estimate field's change

- package-lock.json
- package.json
- src/components/CommentView/CommentView.tsx
- src/components/GoalPreview/GoalPreview.tsx
…ements
Resolve [#1054](https://github.com/taskany-inc/issues/issues/1054)
> CommentView: change comment type when clicking on child elements 

- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/components/ExporeProjectsPage/ExporeProjectsPage.tsx
- src/components/GoalListItem.tsx
- src/components/GoalsGroup.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/ProjectListItem.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/components/Table.tsx
- trpc/queries/goals.ts
- trpc/router/goal.ts
- trpc/router/project.ts
> ProjectListItem redesign

- src/components/EstimateComboBox.tsx
- src/components/GoalForm/GoalForm.tsx
Resolve [#426](https://github.com/taskany-inc/issues/issues/426)
Shifts of quarters relative to Q2 on the goal creation and editing forms
> Estimate must show current Q first and others in future

- src/components/GoalActivity.tsx
> Status updates for goal not visible in preview

- src/components/State.tsx
Resolve [#1040 ](https://github.com/taskany-inc/issues/issues/1040)
> State improvements

- package-lock.json
- package.json
- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/CommentForm/CommentForm.i18n/en.json
- src/components/CommentForm/CommentForm.i18n/ru.json
- src/components/CommentForm/CommentForm.tsx
- src/components/FormEditor/FormEditor.i18n/en.json
- src/components/FormEditor/FormEditor.i18n/ru.json
- src/components/FormEditor/FormEditor.tsx
- src/components/GoalCreateForm/GoalCreateForm.i18n/en.json
- src/components/GoalCreateForm/GoalCreateForm.i18n/ru.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalEditForm/GoalEditForm.i18n/en.json
- src/components/GoalEditForm/GoalEditForm.i18n/ru.json
- src/components/GoalEditForm/GoalEditForm.tsx
- src/components/GoalForm/GoalForm.i18n/en.json
- src/components/GoalForm/GoalForm.i18n/ru.json
- src/components/GoalForm/GoalForm.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/HotkeysModal/HotkeysModal.tsx
- src/components/ModalOnEvent.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.i18n/en.json
- src/components/ProjectCreateForm/ProjectCreateForm.i18n/ru.json
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/components/Tip.tsx
> Create modal improvements

- trpc/router/search.ts
> Limit search results to 5 + 5

- package-lock.json
- package.json
- src/components/ColorizedMenuItem.tsx
- src/components/GoalListItem.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/PriorityDropdown.tsx
Resolve [#1038 ](https://github.com/taskany-inc/issues/issues/1038)
> Priority design improvements

- src/hooks/useHotkeys.ts
Resolve  #1085
- try <kbd>/</kbd> in any input or textarea
> disable hotkeys when an input is in focus

- package-lock.json
- package.json
- src/components/GoalCriteria/GoalCriteria.tsx
> TickCircleIcon: fix typo

- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/PriorityDropdown.tsx
- src/components/PriorityFilter.tsx
- src/components/PriorityText/PriorityText.tsx
- src/hooks/useUrlFilterParams.ts
- src/types/priority.ts
Resolve #1098
Related to #1038
> PriorityDropdown must't be colorful

- src/components/GoalPreview/GoalPreview.i18n/en.json
- src/components/GoalPreview/GoalPreview.i18n/ru.json
- src/components/GoalPreview/GoalPreview.tsx
Resolve [#1108 ](https://github.com/taskany-inc/issues/issues/1108)
> Placeholder for empty description

- src/components/PriorityDropdown.tsx
Resolve #1118
- select ru locale
- try to change priority in goal create or edit form
> Impossible to change goal priority 

- src/components/GoalCreateForm/GoalCreateForm.i18n/en.json
- src/components/GoalCreateForm/GoalCreateForm.i18n/ru.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/hooks/useLocalStorage.ts
Resolve [#1047 ](https://github.com/taskany-inc/issues/issues/1047)
> Create goal button improvements 

- src/utils/db.ts
> Incorrect scopeId for goal in case of deleted goals from db

- src/components/CommentView/CommentView.tsx
- src/components/RelativeTime/RelativeTime.tsx
Resolve [#1087 ](https://github.com/taskany-inc/issues/issues/1087)
> Disable hover for unclickable timestamps

- package-lock.json
- package.json
- prisma/migrations/20230620174150_/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- src/components/GoalPage/GoalPage.i18n/en.json
- src/components/GoalPage/GoalPage.i18n/ru.json
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.i18n/en.json
- src/components/GoalPreview/GoalPreview.i18n/ru.json
- src/components/GoalPreview/GoalPreview.tsx
- src/components/IssueStats/IssueStats.tsx
- src/utils/dateTime.ts
- trpc/queries/goals.ts
> Goal header redesign

- prisma/migrations/20230621101038_/migration.sql
- prisma/schema.prisma
> Goal.scopeId must be uniq

- trpc/router/goal.ts
Resolve #1072
- open goal editing dialog
- try to set existing estimate
- save
- no record in history about estimate changes
> Check estimate changes before adding history item

- trpc/router/goal.ts
> Status change comment can be before or after corresponding history item

- src/utils/getLang.ts
Resolve #1126
Related https://github.com/taskany-inc/issues/issues/1133
- go to /ru page
- page is localized
> Index page is not localized

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- trpc/queries/goals.ts
- trpc/queries/project.ts
> Add counter to Issues Button

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
> Open collapsed goals and children on Project page

- src/components/CommentForm/CommentForm.tsx
- src/components/CommentView/CommentView.tsx
- src/components/DashboardPage/DashboardPage.tsx
- src/components/EstimateComboBox.tsx
- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/components/ExporeProjectsPage/ExporeProjectsPage.tsx
- src/components/GoalForm/GoalForm.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/HelpButton/HelpButton.tsx
- src/components/HelpPage/HelpPage.tsx
- src/components/IssueStats/IssueStats.tsx
- src/components/Page.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- src/components/RelativeTime/RelativeTime.tsx
- src/components/UserInviteForm/UserInviteForm.tsx
- src/components/UserSettingsPage/UserSettingsPage.tsx
- src/hooks/router.ts
- src/hooks/useLocale.ts
- src/pages/_app.tsx
- src/pages/help/[locale]/[slug].tsx
- src/pages/help/[slug].tsx
- src/pages/help/source/ru/welcome.md
- src/utils/declareSsrProps.ts
- src/utils/getLang.ts
- src/utils/pageContext.ts
> Remove client-side locale detection

- src/components/CollapsableItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/Table.tsx
> Highlight collapsable projects in app interface

- src/components/PageHeader/PageHeader.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- trpc/router/project.ts
> /projects impovements

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
> ProjectListItemCollapsable: ghost button to trigger goals 

- src/components/GoalsPage/GoalsPage.tsx
- src/pages/goals/index.tsx
> No SSR on /goals page

- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
- trpc/router/goal.ts
Resolve #1165
Try to change state of not your goal.
> StateSwitch must be interactive if goal is editable only

- src/components/ProjectListItemConnected.tsx
- trpc/router/project.ts
> Create endpoint to get goals by project id

- src/components/CollapsableItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
> Hide border for project without child

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
Resolve #1189 
https://github.com/taskany-inc/issues/assets/9020793/e806108e-27af-48eb-a245-27220cf33f2f
> Remove offset blinking

- package-lock.json
- package.json
- src/components/ActivityFeed.tsx
- src/components/Circle.tsx
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalCriteria/GoalCriteria.i18n/en.json
- src/components/GoalCriteria/GoalCriteria.i18n/ru.json
- src/components/GoalCriteria/GoalCriteria.tsx
- src/schema/criteria.ts
Beautify markup of criteria form and criteria list
Resolve #1103 
Resolve #1104
> Refactor GoalCriteria & Refactor CriteriaForm

- src/components/UserGroup.tsx
Resolve [#1193](https://github.com/taskany-inc/issues/issues/1193)
> Users counter must be circle by default

- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/UserSettingsPage/UserSettingsPage.tsx
Resolve [#1194 ](https://github.com/taskany-inc/issues/issues/1194)
> All primary action buttons must be outline

- src/components/GoalCriteria/GoalCriteria.tsx
> GoalCriteria: move remove button to criteria title

- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
> Do not show zero weight for criteria

- package-lock.json
- package.json
- src/components/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- src/components/Table.tsx
Resolve #1168 
https://github.com/taskany-inc/issues/assets/9020793/7426cb0a-ddc5-4883-a52e-04a61861b977
> find a way to open a Project Page from Projects collapsable list

- src/components/ColorizedMenuItem.tsx
> Return StateDot to comment dropdown 

- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/PriorityDropdown.tsx
- src/components/PriorityText/PriorityText.tsx
Resolve [#1143 ](https://github.com/taskany-inc/issues/issues/1143)
> Remove <PriorityText /> component

- prisma/migrations/20230628205205_/migration.sql
- prisma/schema.prisma
- src/components/BetaBadge.tsx
- src/components/PageHeader/PageHeader.tsx
- src/components/UserSettingsPage/UserSettingsPage.i18n/en.json
- src/components/UserSettingsPage/UserSettingsPage.i18n/ru.json
- src/components/UserSettingsPage/UserSettingsPage.tsx
- src/schema/user.ts
- src/utils/auth.ts
> Beta setting for user

- package-lock.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalEditForm/GoalEditForm.tsx
- src/components/GoalForm/GoalForm.tsx
- src/components/GoalPage/GoalPage.i18n/en.json
- src/components/GoalPage/GoalPage.i18n/ru.json
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalParentComboBox.tsx
- src/components/UserComboBox.tsx
- src/utils/db.ts
- trpc/router/goal.ts
- trpc/router/project.ts
> Add transfer button in GoalPage 

- src/components/CommentForm/CommentForm.tsx
> Impossible comment with push state

- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/DashboardPage/DashboardPage.tsx
- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/components/ExporeProjectsPage/ExporeProjectsPage.tsx
- src/components/GoalListItem.tsx
- src/components/GoalListItemCompact.tsx
- src/components/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemCompact.tsx
- src/components/ProjectListItemConnected.tsx
- src/components/Table.tsx
> Rewrite TableRow component

- src/components/State.tsx
- src/components/StateDot.tsx
> State color changes for white theme

- src/utils/db.ts
Resolve #1231
Try to create goal with tags.
> Error 500 appears when creating/editing a target with a tag

- src/components/TagComboBox.tsx
Resolve [#661 ](https://github.com/taskany-inc/issues/issues/661)
https://github.com/taskany-inc/issues/assets/87986652/dd872b85-9790-4fb2-93a8-6a36abee35a4
> Deleted tags come back after deleting in GoalCreateForm and GoalEditForm

- src/components/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
> Align project list item actions right

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/Table.tsx
Resolve [#1185](https://github.com/taskany-inc/issues/issues/1185)
> Project goals tab design for ProjectListItemCollapsable

- src/components/FiltersPanelApplied/FiltersPanelApplied.tsx
Resolve [#1225 ](https://github.com/taskany-inc/issues/issues/1225)
> 500 on applied preset 

- src/components/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/Table.tsx
Resolve #1186 
https://github.com/taskany-inc/issues/assets/9020793/2197264e-b940-489c-a98e-7e77ebffa3ce
> Projects w/o children must be not interactive

- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/StateSwitch.tsx
- src/schema/goal.ts
- trpc/router/goal.ts
Completed criterias on GoalPage and GoalPreview shows in begin of list
Resolve #1195
> Show achieved criteria first

- src/components/BetaBadge.tsx
- src/components/Circle.tsx
- src/components/GoalDependencyList/GoalDependencyList.tsx
Append Beta mark for new dependecies feature
Resolve #1275
> Mark new dependency feature as Beta

- src/components/FiltersPanel/FiltersPanel.tsx
Resolve #1273 
https://github.com/taskany-inc/issues/assets/9020793/08dd6466-afc0-44c3-8746-a805a27d325b
> Filters: filter shouldn't be hidden with empty search

- trpc/router/goal.ts
> Goal can't be edited by project owner if he's not the goal owner

- src/components/EstimateFilter.tsx
- trpc/router/estimates.ts
> Duplicate estimates in estimate filter

- src/components/CriteriaForm/CriteriaForm.i18n/en.json
- src/components/CriteriaForm/CriteriaForm.i18n/ru.json
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalDependencyForm/GoalDependencyForm.tsx
- src/components/GoalSuggest.tsx
- src/components/InlineForm.tsx
In this PR I was make a several changes:
- append toggle those switch between type of criteria
- append hint for this toggle and submit form helper
- changes in `<InlineForm /> and <GoalSuggest /> components`
Resolve #1198 
Related issues #<issue>, #<issue>
> Criteria suggest doesn't work as expected

- package-lock.json
- package.json
- src/components/EstimateComboBox.tsx
- src/components/FlowComboBox.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalParentComboBox.tsx
- src/components/PageFooter/PageFooter.tsx
- src/components/TagComboBox.tsx
- src/components/UserComboBox.tsx
> Drop trigger ref of ComboBox component 'cause it useless

- src/components/UserGroup.tsx
> user and counter tooltips

- prisma/migrations/20230717111348_/migration.sql
- prisma/schema.prisma
- src/components/GoalListItem.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/GoalsGroup.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/IssueStats/IssueStats.tsx
- src/components/ProjectListItemConnected.tsx
- src/utils/db.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
Resolve #1187 
Dashboard
Goals 
Projects
> Show criteria progress in GoalListItem

- package-lock.json
- package.json
- src/components/ActivityFeed.tsx
- src/components/Circle.tsx
- src/components/CommentView/CommentView.tsx
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalCriteria/GoalCriteria.i18n/en.json
- src/components/GoalCriteria/GoalCriteria.i18n/ru.json
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/ModalOnEvent.tsx
- src/components/Page.tsx
- src/global.d.ts
- src/hooks/useCriteriaResource.ts
- src/schema/criteria.ts
- src/utils/dispatchModal.ts
- trpc/inferredTypes.ts
- trpc/router/goal.ts
Implements feature that allows convert simple criteria into goal
Resolve #1106 
Related issues #<issue>, #<issue>
> Convert simple criteria to goal criteria

- src/components/CommentForm/CommentForm.tsx
Resolve #1210 
https://github.com/taskany-inc/issues/assets/95316053/8642b7e9-7f9a-404a-a5b3-f32518bc4983
> Comment form doesn't close correctly on click outside

- src/components/GoalCriteria/GoalCriteria.tsx
Now a dropdown is disappearing after click by action item
Resolve #1315 
https://github.com/taskany-inc/issues/assets/7002692/69347099-59d2-46db-b54e-567fd95ee9b9
> Dropdown doest'n disappear after modal open in criteria

- src/components/GoalActivity.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
Resolve [#1238 ](https://github.com/taskany-inc/issues/issues/1238)
https://github.com/taskany-inc/issues/assets/87986652/2821d7b3-f106-4e05-8924-f8e4bf46d670
https://github.com/taskany-inc/issues/assets/87986652/160b8595-1341-4f32-b4e8-600fc01079da
> Hide goal description diff in history under cut

- prisma/migrations/20230713092449_/migration.sql
- prisma/schema.prisma
- src/components/GoalActivity.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalSuggest.tsx
- src/components/HistoryRecord/HistoryRecord.i18n/en.json
- src/components/HistoryRecord/HistoryRecord.i18n/ru.json
- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/IssueListItem.tsx
- src/schema/criteria.ts
- src/types/history.ts
- src/utils/db.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
> Save criteria changes to the history

- prisma/migrations/20230718153020_/migration.sql
- prisma/schema.prisma
- src/components/DashboardPage/DashboardPage.tsx
- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/components/ExporeProjectsPage/ExporeProjectsPage.tsx
- src/components/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/utils/db.ts
Resolve #1188 
Related issues #1196 
**NOTE** base branch will change after merge https://github.com/taskany-inc/issues/pull/1294
> Show project score in ProjectListItem

- src/schema/goal.ts
Drop broken validation type
Resolve #1293
> Dependent goals selection is broken

- trpc/router/search.ts
> Global search searches for deleted goals

- src/components/GoalForm/GoalForm.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/StateDropdown.tsx
- src/components/StateSwitch.tsx
> useQuery hooks should not be called conditionally

- src/utils/db.ts
Resolve [#1292 ](https://github.com/taskany-inc/issues/issues/1292)
> Yearly goal estimate doesn't work

- src/components/HistoryRecord/HistoryRecord.i18n/ru.json
> HistoryRecord: spelling issue

- src/components/HistoryRecord/HistoryRecord.tsx
User avatars now showing correctlly by their emails
Resolve #1234
> Avatars disappears in goal history

- trpc/queries/sqlProject.ts
- trpc/router/project.ts
Resolve #1229 
Related issues #1319
> Sort projects by last updated goals

- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalCriteria/GoalCriteria.i18n/en.json
- src/components/GoalCriteria/GoalCriteria.i18n/ru.json
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalDependencyForm/GoalDependencyForm.tsx
- src/components/GoalDependencyList/GoalDependencyList.i18n/en.json
- src/components/GoalDependencyList/GoalDependencyList.i18n/ru.json
- src/components/GoalDependencyList/GoalDependencyList.tsx
- src/components/GoalListItemCompact.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalSuggest.tsx
- src/components/Table.tsx
Apply common styles for Criteria and Deps Tables and Forms
Resolve #1309
> Sync criteria and deps title style

- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
Resolve #1364
https://github.com/taskany-inc/issues/assets/95316053/0204a412-b84b-42a8-b177-7a30d737a259
> Wrong modal behavior

- package-lock.json
- package.json
- src/components/GoalPage/GoalPage.tsx
Resolve [#211](https://github.com/taskany-inc/bricks/issues/211)
> Card: remove specific styles

- src/components/CriteriaForm/CriteriaForm.tsx
- trpc/router/goal.ts
Resolve #1105 
https://github.com/taskany-inc/issues/assets/95316053/a1c8c3e1-3ab1-476b-977e-cc59aad59ce9
> Save last created goals for criteria suggest

- package-lock.json
- package.json
- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/CommentForm/CommentForm.tsx
- src/hooks/useCommentResource.ts
Resolve #1326 
https://github.com/taskany-inc/issues/assets/95316053/1b96f812-9528-4715-a921-ba177824e84f
> Comment form doesn't allow click inside after comment submit

- src/utils/db.ts
Resolve #1378
Resolve #1312 
Resolve #1383 
add deps in one goal, after reopen this goal
or
transfer goal between projects
> Linked goal page is broken

- trpc/queries/goals.ts
Resolve [#1320](https://github.com/taskany-inc/issues/issues/1320)
> Project filter on goals page can't find goals inside child projects

- src/components/GoalEditForm/GoalEditForm.tsx
Resolve #1384 
https://github.com/taskany-inc/issues/assets/95316053/abf162e3-0abe-42cf-89c7-c1483be418b3
> Error saving estimate in RU locale

- next.config.js
Resolve [#1404](https://github.com/taskany-inc/issues/issues/1404)
> always use reactStrictMode=true

- src/pages/_app.tsx
> Init const themes outside App component's render 

- src/components/FiltersPanel/FiltersPanel.tsx
Resolve [#1408](https://github.com/taskany-inc/issues/issues/1408)
> Extra refetch data in FiltersPanel on client

- package-lock.json
- package.json
- src/components/PageFooter/PageFooter.tsx
> Change PageFooter import to bricks root 

- src/components/NotificationsHub/NotificationHub.map.ts
- src/components/NotificationsHub/NotificationsHub.tsx
- src/utils/dispatchNotification.ts
- src/utils/notifyPromise.ts
Resolve [#1381 ](https://github.com/taskany-inc/issues/issues/1381)
> Toasts are always in en locale

- src/utils/db.ts
Resolve #1422 
Related issues #<issue>, #<issue>
> Converting number to boolean into history is crashed app

- src/components/GoalPreview/GoalPreview.tsx
Resolve [#1389 ](https://github.com/taskany-inc/issues/issues/1389)
> To much bottom padding in GoalPreview

- src/components/EstimateComboBox.tsx
- src/utils/dateTime.test.ts
- src/utils/dateTime.ts
Resolve #1397 
https://github.com/taskany-inc/issues/assets/95316053/f4c1bcf9-1bee-4455-888c-fa89cb068193
> Estimate form is not working

- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/CommentEditForm/CommentEditForm.tsx
- src/components/CommentForm/CommentForm.tsx
Resolve #1425
1. Go to any goal
2. Click on comment field
3. Choose another status in the dropdown
4. Text in comment still exists
> Comment form clears comment text on status change

- next.config.js
- package-lock.json
- package.json
- src/components/CriteriaForm/CriteriaForm.i18n/en.json
- src/components/CriteriaForm/CriteriaForm.i18n/ru.json
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalActivity.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalDependencyList/GoalDependencyList.tsx
- src/components/GoalListItemCompact.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/GoalSuggest.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/InlineForm.tsx
- src/hooks/useCriteriaResource.ts
- src/schema/criteria.ts
- trpc/router/goal.ts
> User can edit criteria

- src/components/GoalCriteria/GoalCriteria.tsx
Now unique title validation works correctly
Resolve #1440 
1. Try to pass same criteria title by add or edit
> Broken title filed validation in criteria

- src/components/CommentView/CommentView.tsx
Resolve [#1424 ](https://github.com/taskany-inc/issues/issues/1424)
> With a long comment, the form and comment are expanded in GoalPreview

- Dockerfile
- [ x] Bug Fix
Fixed worker path
Resolve #1449
> Worker is not found on docker start

- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/GoalActivity.tsx
- src/hooks/useLSDraft.ts
- src/hooks/useLocalStorage.ts
- src/types/draftComment.ts
Resolve #1251 
https://github.com/taskany-inc/issues/assets/95316053/02c8f614-89e5-4878-8a1c-206414c454a1
> Save comment drafts in localstorage

- src/components/StateSwitch.tsx
> Status picker in goal preview looks bad

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
> Fix collapsable Item state

- src/components/GoalPreview/GoalPreview.tsx
- src/components/Page.tsx
> Dynamic load for GoalPreview 

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
Resolve #1482 
https://github.com/taskany-inc/issues/assets/9020793/a80f78f3-0086-403c-a574-741a96e5d0c2
> Show projects without goals

- src/components/GoalPage/GoalPage.tsx
> TypeError: undefined is not an object (evaluating 't.id') 

- src/components/GlobalSearch/GlobalSearch.tsx
> TypeError: Cannot read properties of undefined (reading '__kind') 

- src/components/GoalPage/GoalPage.tsx
> TypeError: Cannot read properties of undefined (reading 'id') 

- prisma/migrations/20230809142748_change_values_to_match_sql/migration.sql
- prisma/schema.prisma
> fix(Database): use re-generate migration to match db values

- src/components/GoalPreview/GoalPreview.tsx
- src/components/Page.tsx
Resolve #1486 
_Please replace this line with instructions on how to test your changes, a note on the devices and browsers this has been tested on, as well as any relevant images for UI changes._
https://github.com/taskany-inc/issues/assets/9020793/d95c244f-ddd1-46d6-99f0-b1427d503c28
> Goal preview stays open after opening goal page

- trpc/router/project.ts
> Incorrect goals filtering on dashboard

- .env.ci
- app_run.ci.sh
- package.json
- prisma/seed.ts
- scripts/fillDevData.ts
Resolve #1524
Related issues #119
> Remove fake data from seed script 

- src/components/FeedbackCreateForm/FeedbackCreateForm.tsx
- trpc/router/feedback.ts
Resolve [#1528 ](https://github.com/taskany-inc/issues/issues/1528)
> Feedback form not closing on success

- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/ImageFullScreen.tsx
- src/components/Page.tsx
Resolve [#1507 ](https://github.com/taskany-inc/issues/issues/1507)
> ImagePreview closes GoalPreview on ESC

- src/components/GoalDependencyList/GoalDependencyList.tsx
Resolve [#1539 ](https://github.com/taskany-inc/issues/issues/1539)
> The escaped circle 

- src/utils/worker/index.ts
> Sentry exception on last retry in jobs resolver

- trpc/router/project.ts
> Return firstLevel param to project.getAll

- src/components/FiltersPanelApplied/FiltersPanelApplied.tsx
- src/components/StateFilter.tsx
> FiltersApplied is not available when default filter applied

- package-lock.json
- package.json
- src/components/DashboardPage/DashboardPage.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/pages/_app.tsx
- src/utils/telemetry.ts
> Real-user performance monitoring

- CONTRIBUTING.md
> Cleanup old info from CONTRIBUTING.md

- trpc/router/project.ts
> Projects page doesn't show projects with multiple children

- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalListItemCompact.tsx
> Do not show icon for goals in GlobalSearch

- src/components/GoalPage/GoalPage.i18n/en.json
- src/components/GoalPage/GoalPage.i18n/ru.json
- src/components/GoalPage/GoalPage.tsx
- src/components/TagComboBox.tsx
Resolve [#1233 ](https://github.com/taskany-inc/issues/issues/1233)
https://github.com/taskany-inc/issues/assets/87986652/b0f67074-4a2c-4120-b4e3-355bf94aee0d
> Show goal tags in sidebar

- src/components/HistoryRecord/HistoryRecord.tsx
> Incorrect Year Estimate label

- src/utils/filters.ts
Resolve #1597 
https://github.com/taskany-inc/issues/assets/9020793/34453d2d-48ad-40aa-969c-03502e6291b8
> No way to select custom preset in FIltersPanel

- src/components/EstimateFilter.tsx
- src/components/FiltersPanelApplied/FiltersPanelApplied.tsx
- src/utils/estimateToString.ts
- trpc/queries/goals.ts
Resolve #1593
https://github.com/taskany-inc/issues/assets/9020793/3d659efa-2adc-4595-aba4-7230cbcea85d
> Estimate filter doesn't work with years

- src/utils/filters.ts
Resolve #1607 
https://github.com/taskany-inc/issues/assets/9020793/70a23f91-57c2-46c8-a284-28bf1f79f60f
> Presets don't work on SSR side

- src/components/DashboardPage/DashboardPage.tsx
- src/components/GoalsGroup.tsx
- src/hooks/useUrlFilterParams.ts
> Fix memoization for GoalsGroup

- src/components/DashboardPage/DashboardPage.tsx
- src/components/ExploreProjectsPage/ExploreProjectsPage.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- src/pages/index.tsx
- src/pages/projects/index.tsx
- trpc/router/project.ts
Resolve #1501 
Resolve #1561
dashboard page
https://github.com/taskany-inc/issues/assets/95316053/be7518df-495a-48b7-8863-f1f2f9386ac6
projects page
https://github.com/taskany-inc/issues/assets/95316053/2ad6388f-5ec5-4180-85b2-63ee72e1a6e6
> Pagination for / and /projects pages

- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
> User can create goal criteria everywhere

- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/WhatsNew/WhatsNew.tsx
- src/utils/trpcClient.ts
> Drop redundant data refetch on the client

- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalEditForm/GoalEditForm.tsx
Resolve #1431 
https://github.com/taskany-inc/issues/assets/9020793/19b94b52-f985-4e55-a3bb-eee1aa4d2b0e
> Project page doesn't updates after goal creating

- src/utils/worker/create.ts
- src/utils/worker/mail/templates.ts
- trpc/router/goal.ts
- trpc/router/project.ts
Resolve #1547 
Related issues #1668
> Do not send email if author unassigned himself

- src/components/UserSettingsPage/UserSettingsPage.i18n/en.json
- src/components/UserSettingsPage/UserSettingsPage.i18n/ru.json
- src/components/UserSettingsPage/UserSettingsPage.tsx
- trpc/router/user.ts
Resolve [#160 ](https://github.com/taskany-inc/issues/issues/160)
> Validate unique nickname field on settings page

- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalPage/GoalPage.tsx
- src/hooks/useGoalResource.ts
- trpc/router/goal.ts
Resolve #1635 
Resolve #1660 
Resolve #1659 
https://github.com/taskany-inc/issues/assets/95316053/fd4cd137-16e0-4b33-b2d9-f3db0b804ab7
> Goal update separation

- src/components/GoalPage/GoalPage.tsx
Resolve #1634 
https://github.com/taskany-inc/issues/assets/95316053/e4640903-ff62-473a-9110-36c69a7bf25e
> User can remove tags from GoalPage

- src/components/EstimateFilter.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/utils/dateTime.ts
Resolve #1134 
https://github.com/taskany-inc/issues/assets/9020793/426ccdd7-19d6-4b01-b158-4806c076ca98
> Support @pevious, @current, @next in estimate filters

- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalEditForm/GoalEditForm.tsx
- src/components/GoalForm/GoalForm.tsx
- src/components/UserSettingsPage/UserSettingsPage.tsx
- src/hooks/useGoalResource.ts
- src/schema/common.ts
- src/schema/criteria.ts
- trpc/router/goal.ts
Resolve [#1683 ](https://github.com/taskany-inc/issues/issues/1683)
> Correct a spelling mistake

- .eslintrc.js
Resolve #1096
```
➜  issues git:(issues/1096) ✗ npm run lint
> @taskany/issues@1.31.0 lint
> next lint && eslint --ext .js,.ts,.tsx .
- info Loaded env from /Users/tony_vi/Documents/Source/taskany-inc/issues/.env
./src/components/GoalListItemCompact.tsx
36:49  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
41:41  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
56:70  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
71:31  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
./src/components/GoalSuggest.tsx
14:21  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
./src/hooks/useGoalResource.ts
20:42 …
```
> Prefer destruction in must cases 

- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalDependencyForm/GoalDependencyForm.tsx
- src/components/GoalSuggest.tsx
- src/components/HotkeysModal/HotkeysModal.tsx
- src/components/UserSettingsPage/UserSettingsPage.tsx
> Drop unnecessary Effects

- src/components/GoalPage/GoalPage.tsx
- src/components/IssueStats/IssueStats.tsx
- src/components/RelativeTime/RelativeTime.tsx
> Goal header is broken 

- src/components/ProjectsPage/ProjectsPage.tsx
- src/pages/projects/[id]/settings.tsx
- trpc/router/project.ts
> Project._isEditable

- src/components/CardHeader.tsx
- src/components/CommentView/CommentView.tsx
- src/components/DashboardPage/DashboardPage.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- src/components/UserBadge.tsx
- src/components/UserComboBox.tsx
- src/components/UserFilter/UserFilter.tsx
- src/components/UserGroup.tsx
- src/utils/getUserName.ts
- trpc/router/user.ts
Fix all places where using user data
Resolve #1710
> Show email if user don't have name in goal description

- cypress/e2e/projects.cy.ts
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/utils/keyPredictor.test.ts
- src/utils/keyPredictor.ts
Now we have a correct error message in tests
Resolve #1535
> Incorrect error message on existing project

- cypress/e2e/dashboard.cy.ts
- cypress/e2e/projects.cy.ts
- src/components/DashboardPage/DashboardPage.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/FiltersPanelApplied/FiltersPanelApplied.tsx
- src/components/ProjectListItemConnected.tsx
- src/hooks/useUrlFilterParams.ts
- src/utils/domObjects.ts
- trpc/router/project.ts
Resolve #1643 
https://github.com/taskany-inc/issues/assets/95316053/88a22876-80cc-4bcb-8430-8323dfe40781
> Empty projects shown on dashboard

- .env.ci
- app_run.ci.sh
- src/utils/auth.ts
> Disable password auth in production

- trpc/access/accessCheckers.ts
- trpc/access/accessEntityGetters.ts
- trpc/access/accessMiddlewares.ts
- trpc/queries/project.ts
- trpc/router/goal.ts
- trpc/router/project.ts
- trpc/trpcBackend.ts
> Middleware to check possibility to edit goal/comment and etc

- src/components/GoalPage/GoalPage.tsx
> Any user can remove tag from any goal

- src/components/GoalActivityFeed.tsx
- src/components/GoalContentHeader/GoalContentHeader.i18n/en.json
- src/components/GoalContentHeader/GoalContentHeader.i18n/index.ts
- src/components/GoalContentHeader/GoalContentHeader.i18n/ru.json
- src/components/GoalContentHeader/GoalContentHeader.tsx
- src/components/GoalHeader.tsx
- src/components/GoalPage/GoalPage.i18n/en.json
- src/components/GoalPage/GoalPage.i18n/ru.json
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.i18n/en.json
- src/components/GoalPreview/GoalPreview.i18n/ru.json
- src/components/GoalPreview/GoalPreview.tsx
- src/components/GoalSidebar/GoalSidebar.i18n/en.json
- src/components/GoalSidebar/GoalSidebar.i18n/index.ts
- src/components/GoalSidebar/GoalSidebar.i18n/ru.json
- src/components/GoalSidebar/GoalSidebar.tsx
- src/components/Page.tsx
Resolve #1430 
Resolve #1718 
related to the #1718 
https://github.com/taskany-inc/issues/assets/95316053/51062f18-a541-4c97-a8fe-c19317c965f0
in #1715 block is scrolling horizontally because a long line of text is not being automatically wrapped onto the next line by default, causing the content to extend beyond the visible area.
> Merge GoalPage with GoalPreview

- trpc/access/accessEntityGetters.ts
- trpc/access/accessMiddlewares.ts
- trpc/router/goal.ts
Resolve #1771 
https://github.com/taskany-inc/issues/assets/95316053/0aaf24f8-f4b1-46b4-954e-9d8b3fad12d9
> 500 on criteria add

- src/components/FilterPopup/FilterPopup.tsx
Resolve #1733 
Looks like dirty hack :)
> Catch FilterModal outside click

- src/components/ActivityFeed.tsx
- src/components/CommentView/CommentView.tsx
- src/components/Md.tsx
Resolve #1715 
https://github.com/taskany-inc/issues/assets/95316053/9fd11362-2dc7-47f1-8758-026e4a2a6465
https://github.com/taskany-inc/issues/assets/95316053/01769d77-9321-4bd3-9c92-37a8fc5b12e0
> Horizontal scroll in GoalPreview

- src/components/DashboardPage/DashboardPage.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- src/hooks/useUrlFilterParams.ts
- src/pages/explore/projects.tsx
- src/utils/filters.ts
> Filter label must be highlighted if any param is applied

- src/components/FiltersPanel/FiltersPanel.tsx
- src/utils/filters.ts
Resolve #1780 
https://github.com/taskany-inc/issues/assets/9020793/19bec825-7dc8-4a74-b288-642bb315c178
> User can't change default preset

- src/hooks/useGoalResource.ts
- trpc/access/accessEntityGetters.ts
- trpc/router/goal.ts
Resolve #1790 
https://github.com/taskany-inc/issues/assets/95316053/58401d79-096b-48bb-ad89-fc29523764a8
> Goal comment is not deleted

- package-lock.json
- package.json
Resolve #1782 
https://github.com/taskany-inc/issues/assets/95316053/ca41ffeb-045c-49bf-9f17-831134d148c2
> Jumping search icon

- src/components/DashboardPage/DashboardPage.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- src/components/UserComboBox.tsx
- src/types/history.ts
- src/utils/db.ts
- src/utils/getUserName.ts
- trpc/queries/goals.ts
Now in suggest single item component is correctly get user info
Resolve #1783  
Resolve #1769 
Before needs create activity with ghost field
Then open goal create form and type email of ghost user
or
Go to goal page and try change assignee or participants with ghost user email
> Crash after search in UserComboBox

- package-lock.json
- package.json
- src/components/CriteriaForm/CriteriaForm.tsx
Resolve #1785 
https://github.com/taskany-inc/issues/assets/95316053/ed967425-1c3f-4a98-bf50-758d8e8b2af8
> User can't Edit Criteria

- .github/workflows/e2e.yml
- cypress.config.ts
- cypress/e2e/dashboard.cy.ts
- cypress/e2e/goals.cy.ts
- cypress/e2e/projectSettings.cy.ts
- cypress/e2e/projects.cy.ts
- cypress/index.d.ts
- cypress/plugins/db.ts
- cypress/plugins/index.ts
- cypress/support/index.ts
- src/components/CommonCombobox.tsx
- src/components/CommonDropdown.tsx
- src/components/EstimatePopup.tsx
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalForm/GoalForm.tsx
- src/components/GoalHeader.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalParentComboBox.tsx
- src/components/IssueParent.tsx
- src/components/IssueTitle.tsx
- src/components/Page.tsx
- src/components/PriorityDropdown.tsx
- src/components/ProjectMenuItem.tsx
- src/components/StateDropdown.tsx
- src/components/TagComboBox.tsx
- src/components/UserComboBox.tsx
- src/utils/domObjects.ts
- trpc/router/flow.ts
Add specs for goal create functionality
Also add server tasks for db manipulation
Resolve #1642
> E2E: Goal /create

- src/components/GoalActivityFeed.tsx
- src/components/GoalCommentCreateForm.tsx
- src/components/ProjectsPage/ProjectsPage.tsx
- src/hooks/useGoalResource.ts
- src/hooks/useLSDraft.ts
- src/hooks/useLatest.ts
- src/hooks/useLocalStorage.ts
Resolve #1737 
https://github.com/taskany-inc/issues/assets/95316053/94eb8955-34d9-4fea-9166-379fd2249eaf
> Goal preview re-renders on new comment input

- package-lock.json
- package.json
- src/components/IssueParent.tsx
> Links to project and parent are not working

- src/components/HistoryRecord/HistoryRecord.tsx
> Align cut icon

- src/components/CardHeader.tsx
- src/components/RelativeTime/RelativeTime.tsx
> Align description date with description 

- src/components/IssueTitle.tsx
> Navigating with goal title in goal preview is not working

- src/components/CommentView/CommentView.tsx
- src/components/GoalContentHeader/GoalContentHeader.tsx
> Navigator is undefined

- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/TextList.tsx
> Remove unnecessary styles from TextList 

- src/components/IssueParent.tsx
- src/components/IssueTitle.tsx
- src/components/NextLink.tsx
- src/components/ProjectBadge.tsx
> Remove link props from DOM

- src/components/CommentView/CommentView.tsx
Resolve #1754 
https://github.com/taskany-inc/issues/assets/95316053/89cbc36a-75c3-41a4-8bfb-bd1fd718953f
> Use state dot for pinned comment

- package-lock.json
- prisma/migrations/20231008175304_/migration.sql
- prisma/schema.prisma
- src/components/GoalActivity.tsx
- src/components/GoalSidebar/GoalSidebar.i18n/en.json
- src/components/GoalSidebar/GoalSidebar.i18n/ru.json
- src/components/GoalSidebar/GoalSidebar.tsx
- src/components/HistoryRecord/HistoryRecord.i18n/en.json
- src/components/HistoryRecord/HistoryRecord.i18n/ru.json
- src/components/HistoryRecord/HistoryRecord.tsx
- src/hooks/useGoalResource.ts
- src/schema/goal.ts
- src/types/history.ts
- src/utils/db.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
- trpc/router/project.ts
> Cross project goals

- prisma/migrations/20231013090023_/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalForm/GoalForm.tsx
- src/schema/goal.ts
> Make default priority editable

- cypress/e2e/goals.cy.ts
- cypress/e2e/projects.cy.ts
- cypress/index.d.ts
- cypress/support/index.ts
- prisma/migrations/20231012123728_goal_fields_cascade_delete/migration.sql
- prisma/schema.prisma
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalDeleteModal/GoalDeleteModal.tsx
- src/components/GoalEditForm/GoalEditForm.tsx
- src/components/GoalHeader.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalSidebar/GoalSidebar.tsx
- src/components/InlineTrigger.tsx
- src/components/IssueParent.tsx
- src/components/IssueTitle.tsx
- src/utils/domObjects.ts
> e2e test access to create/edit/delete goals

- src/components/HistoryRecord/HistoryRecord.tsx
> HistoryRecord i18n is missed

- package-lock.json
- package.json
- src/components/CommentView/CommentView.tsx
- src/components/GoalContentHeader/GoalContentHeader.tsx
- src/components/GoalCreateForm/GoalCreateForm.tsx
> Popup must fit content

- src/components/FilteredPage/FilteredPage.tsx
> Filter menu is not highlighted

- src/components/PageHeader/PageHeader.tsx
> Goals page is not Beta 

- src/components/GoalsPage/GoalsPage.tsx
> Disable Group FilterPanel option

- src/components/GoalPreview/GoalPreview.tsx
> Return drop shadow for GoalPreview header

- src/components/GoalListItem.tsx
> Align updatedAt time to left

- src/components/GoalDeleteModal/GoalDeleteModal.i18n/en.json
- src/components/GoalDeleteModal/GoalDeleteModal.i18n/ru.json
- src/components/GoalDeleteModal/GoalDeleteModal.tsx
- src/components/GoalSidebar/GoalSidebar.i18n/ru.json
> Archive goal not delete

- src/components/GoalsPage/GoalsPage.tsx
- src/hooks/useFiltersPreset.ts
- src/hooks/useUrlFilterParams.ts
> Revert: Enable Group/Ungroup control

- package-lock.json
- package.json
- src/components/GroupedGoalList.tsx
- src/components/ProjectListItemConnected.tsx
Now projects in Goals page collapsed by default
Resolve #1886
> The chaos of loading goals in grouped view on /goals page

- package-lock.json
- package.json
- src/components/CommentView/CommentView.tsx
- src/components/CommentsCountBadge.tsx
- src/components/GoalContentHeader/GoalContentHeader.tsx
- src/components/GoalListItem.tsx
- src/components/Light.tsx
- src/components/PageFooter/PageFooter.tsx
- src/components/ReactionsDropdown.tsx
- src/components/RelativeTime/RelativeTime.tsx
Resolve #1813 
https://github.com/taskany-inc/issues/assets/95316053/7644d318-c6b6-4433-ab36-ae96a57a7ab3
https://github.com/taskany-inc/issues/assets/95316053/f0e275ae-8f99-4563-a3c1-ce02339da929
> Link is blue, action is textColor

- src/components/ProjectListItemConnected.tsx
Now after archive goal runs invalidate correctly
Resolve #1845
> Deleted goal remains on the GoalsPage

- src/components/ProjectListItemConnected.tsx
- trpc/router/project.ts
Resolve #1902 
https://github.com/taskany-inc/issues/assets/95316053/c036f81b-087e-4e8d-8f59-154d4a289f52
> Do not show empty projects if filters applied

- src/components/GoalCriteria/GoalCriteria.tsx
> GoalCriteria shouldn't layout shift

- src/utils/auth.ts
> Activity duplicates for existing users

- src/components/RelativeTime/RelativeTime.tsx
> Do not capitalize inline RelativeDate

- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/GoalActivityFeed.tsx
- src/components/GoalCommentCreateForm.tsx
Resolve #1755 
https://github.com/taskany-inc/issues/assets/95316053/7d91d57d-227b-4ab9-93e5-c555fe4c0cbf
> Current state for push comment by default

- cypress/e2e/projects.cy.ts
- src/utils/keyPredictor.ts
Resolve #1917 
https://github.com/taskany-inc/issues/assets/95316053/e3b82767-33d8-4b9c-a220-7c9afd5d5b31
> RU to EN in project key

- src/components/GoalSidebar/GoalSidebar.tsx
Resolve #1988 
https://github.com/taskany-inc/issues/assets/95316053/52476eb3-d493-43a0-bce6-193bea49fce7
https://github.com/taskany-inc/issues/assets/95316053/a6038675-f30c-4794-9055-17f06432cc07
> Default user should not have ability to remove partnership projects & tags

- cypress/e2e/goals.cy.ts
- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/CommentView/CommentView.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/PageHeader/PageHeader.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/UserBadge.tsx
- src/components/UserComboBox.tsx
Resolve #1912 
Tests worked on top of a bug because the user’s avatar in the `<ComboBox />` did not have initials. Now, instead of an exact match, the occurrence is checked because `$el.text()` gets the initials along with the email/name/nickname.
> There no initials on default avatar

- package-lock.json
- package.json
> Project list item wrap

- src/components/GoalDependencyList.tsx
- src/components/GoalSidebar/GoalSidebar.tsx
- src/schema/goal.ts
- src/utils/db.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
Resolve #1833 
https://github.com/taskany-inc/issues/assets/95316053/2399acc2-8f27-494e-a55b-53b7c2974c56
https://github.com/taskany-inc/issues/assets/95316053/26aa13f8-d8b2-419e-a26a-14e6cc658dab
https://github.com/taskany-inc/issues/assets/95316053/6367ba91-c2bc-4569-ab36-45797233d5fc
https://github.com/taskany-inc/issues/assets/95316053/f38753b1-4a22-47e2-9dec-f2dcfa1c4dd3
https://github.com/taskany-inc/issues/assets/95316053/cb923aae-ef40-4b9b-96c4-42756166e470
https://github.com/taskany-inc/issues/assets/95316053/cb83254e-64b3-4fcc-a6f4-1aeb0626b74b
> Related goals must view this relations in related deps

- package-lock.json
- package.json
- src/components/CriteriaFormV2/CriteriaForm.tsx
- src/components/CriteriaFormV2/CriteriaFormV2.i18n/en.json
- src/components/CriteriaFormV2/CriteriaFormV2.i18n/index.ts
- src/components/CriteriaFormV2/CriteriaFormV2.i18n/ru.json
- src/hooks/useForkedRef.ts
New implementation of Criteria Form
Can be use for adding or editing criteria, also creating criteria from current goal / issue in the other goal
Resolve #1961 
Usage
```ts
interface CriteriaFormProps {
// suggest items
items: SuggestItem[];
// default selected mode: simple criteria or goal in current implementation
defaultMode?: CriteriaFormMode;
// allow hide radio button for control form mode
withModeSwitch?: boolean;
// form values for edit early saved criteria
values?: Partial<CriteriaFormValues>;
// additional data for validate form data
validityData: { title: string[]; sumOfCriteria: number };
// action callbacks
onModeChange?: (mode: CriteriaFormMode) => void;
onSubmit: (values: CriteriaFormValues) => void;
onCancel: () => void;
onItemChange?: (item?: SuggestItem) => void; …
```
> Goal Criteria form redesign

- src/components/CriteriaForm/CriteriaForm.i18n/en.json
- src/components/CriteriaForm/CriteriaForm.i18n/ru.json
- src/components/GoalCreateForm/GoalCreateForm.i18n/en.json
- src/components/GoalCreateForm/GoalCreateForm.i18n/ru.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalEditForm/GoalEditForm.i18n/en.json
- src/components/GoalEditForm/GoalEditForm.i18n/ru.json
- src/components/GoalEditForm/GoalEditForm.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.i18n/en.json
- src/components/ProjectCreateForm/ProjectCreateForm.i18n/ru.json
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/components/RotatableTip/RotatableTip.i18n/en.json
- src/components/RotatableTip/RotatableTip.i18n/index.ts
- src/components/RotatableTip/RotatableTip.i18n/ru.json
- src/components/RotatableTip/RotatableTip.tsx
- src/components/UserInviteForm/UserInviteForm.i18n/en.json
- src/components/UserInviteForm/UserInviteForm.i18n/ru.json
- src/components/UserInviteForm/UserInviteForm.tsx
- src/components/UserSettingsPage/UserSettingsPage.i18n/en.json
- src/components/UserSettingsPage/UserSettingsPage.i18n/ru.json
- src/components/UserSettingsPage/UserSettingsPage.tsx
Resolve #1726 
https://github.com/taskany-inc/issues/assets/95316053/b7521ff3-3d73-48cd-9ce2-0ac5a3099363
> Rotatable Tip

- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.tsx
- src/components/GoalSidebar/GoalSidebar.tsx
- src/hooks/useGoalResource.ts
Resolve #1853 
https://github.com/taskany-inc/issues/assets/95316053/fccbe7b9-e6bc-493e-8032-4c2610345b65
https://github.com/taskany-inc/issues/assets/95316053/17038a59-e59a-4881-b72b-3054b3e5bcd8
https://github.com/taskany-inc/issues/assets/95316053/c2fe16ee-4c0a-4adc-a4cb-65c5e14f5d15
https://github.com/taskany-inc/issues/assets/95316053/748d3cb9-2b1e-4994-abac-4c742461bc3b
> Move fully copied handlers to useGoalsResources

- package-lock.json
- package.json
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/EstimateDate/EstimateDate.tsx
- src/components/FeedbackCreateForm/FeedbackCreateForm.tsx
- src/components/FilterAutoCompleteInput/FilterAutoCompleteInput.tsx
- src/components/FilterCreateForm/FilterCreateForm.tsx
- src/components/FlowComboBox.tsx
- src/components/GoalDeleteModal/GoalDeleteModal.tsx
- src/components/GoalForm/GoalForm.tsx
- src/components/GoalParentComboBox.tsx
- src/components/KeyInput.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/SearchFilter.tsx
- src/components/TagComboBox.tsx
- src/components/UserComboBox.tsx
- src/components/UserInviteForm/UserInviteForm.tsx
- src/components/UserSettingsPage/UserSettingsPage.tsx
Resolve #1998 
**1)**
**2)**
**3)**
**4)**
**5)**
**6)**
> Change all inputs to new field error component from bricks

- README.md
- src/instrumentation.node.ts
Resolve [2027](https://github.com/taskany-inc/issues/issues/2027)
> Improve opentelemetry dx

- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.i18n/en.json
- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.i18n/index.ts
- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.i18n/ru.json
- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.tsx
- src/components/ProjectParticipants/ProjectParticipants.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/UserEditableList/UserEditableList.tsx
- src/utils/dispatchModal.ts
- trpc/router/project.ts
Resolve #2034 
https://github.com/taskany-inc/issues/assets/9020793/ea997715-90d4-4de2-8db1-8401b34527b8
> Create a warning modal for participants remove

- src/components/AddInlineTrigger.tsx
- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.i18n/en.json
- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.i18n/index.ts
- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.i18n/ru.json
- src/components/ParticipantDeleteErrorModal/ParticipantDeleteErrorModal.tsx
- src/components/ProjectParticipants/ProjectParticipants.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/UserEditableList/UserEditableList.tsx
- src/pages/goals/[id].tsx
- src/pages/goals/index.tsx
- src/pages/projects/[id]/index.tsx
- src/pages/projects/[id]/settings.tsx
- src/schema/goal.ts
- src/utils/dispatchModal.ts
- trpc/access/accessCheckers.ts
- trpc/access/accessEntityGetters.ts
- trpc/access/accessMiddlewares.ts
- trpc/queries/access.ts
- trpc/queries/goals.ts
- trpc/queries/project.ts
- trpc/router/goal.ts
- trpc/router/project.ts
- trpc/router/search.ts
Resolve #2032 
https://github.com/taskany-inc/issues/assets/9020793/728e326a-a7ec-4fd2-99b9-30cbf0fa6471
> Hide a private goals and projects

- prisma/migrations/20231114134050_one_to_many_goal_is_criteria_relation/migration.sql
- prisma/schema.prisma
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
- src/types/history.ts
- src/utils/db.ts
- src/utils/recalculateCriteriaScore.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
Now can be link one goal to many criterias
Added a new column `criteriaGoalId` to `GoalAchieveCriteria` model
Added a new relation `goalInCriteria` between `Goal` and `GoalAchieveCriteria` model
Resolve #2000
Resolve #1752
> one-to-many criteria to goals relation

- src/components/CriteriaForm/CriteriaForm.i18n/en.json
- src/components/CriteriaForm/CriteriaForm.i18n/ru.json
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalActivityFeed.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/VersaCriteria/VersaCriteria.tsx
- trpc/router/goal.ts
> Bugs in criteria feature

- cypress/e2e/projectSettings.cy.ts
The simpler the better
Resolve #2022
> e2e: Fix auth test problem

- src/components/ProjectPageTabs/ProjectPageTabs.tsx
> Hide alone Goals tab

- src/components/CommentView/CommentView.tsx
> Show avatar with state comment

- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/CommentForm/CommentForm.tsx
- src/components/CommentView/CommentView.tsx
Resolve #2087 
https://github.com/taskany-inc/issues/assets/95316053/02c4d34c-6fb9-49ad-b2c3-c302738f9690
> Fix submit comment form

- package-lock.json
- package.json
- src/pages/api/upload.ts
Resolve #2084 
Related issues https://github.com/taskany-inc/bricks/issues/651
> Return type & name from uploaded files

- src/utils/prepareRecipients.ts
- src/utils/worker/create.ts
- src/utils/worker/mail/templates.ts
- trpc/router/goal.ts
- trpc/router/project.ts
> Email notifictaion on add/remove partner project to goal

- src/components/GoalActivity.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
- src/types/history.ts
- src/utils/db.ts
- trpc/queries/goals.ts
Simplify types of `GoalHistory`, simplify usage components
Resolve #2043 
Related issues #1753
> Rewrite history records types

- src/components/GoalActivity.tsx
- src/components/HistoryRecord/HistoryRecord.i18n/en.json
- src/components/HistoryRecord/HistoryRecord.i18n/ru.json
- src/components/HistoryRecord/HistoryRecord.tsx
Grouping the same records of goal's history
Resolve #1753
> Collect same history records in view

- src/components/ProjectAccessUser/ProjectAccessUser.tsx
- src/components/ProjectParticipants/ProjectParticipants.i18n/en.json
- src/components/ProjectParticipants/ProjectParticipants.i18n/index.ts
- src/components/ProjectParticipants/ProjectParticipants.i18n/ru.json
- src/components/ProjectParticipants/ProjectParticipants.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/ProjectSettingsUserList.tsx
- src/components/UserEditableList/UserEditableList.tsx
- src/hooks/useProjectResource.ts
- src/schema/project.ts
- src/utils/worker/mail/templates.ts
- trpc/router/project.ts
Resolve #2108 
https://github.com/taskany-inc/issues/assets/95316053/f2676395-a75d-4f0e-b861-d15448544a3b
> Allow participants editing in project settings

- package-lock.json
- package.json
- src/utils/worker/create.ts
- src/utils/worker/index.ts
- src/utils/worker/resolve.ts
> Worker Cron Support 

- cypress/e2e/goals.cy.ts
> Fix goals and comments tests

- prisma/migrations/20231218143513_remove_owners_from_participants_lists/migration.sql
- src/hooks/useGoalResource.ts
- src/utils/db.ts
Resolve #1908 
Resolve #2120 
https://github.com/taskany-inc/issues/assets/95316053/a2f500b3-3f3a-4d52-9aa0-723b8c90a525
> Do not show project owner in project participants

- src/components/CommentView/CommentView.tsx
- src/components/GoalActivity.tsx
- src/components/GoalActivityFeed.tsx
- src/hooks/useGoalResource.ts
- src/types/comment.ts
> Refactor component types

- cypress/fixtures/langs.json
- src/components/GoalHeader.tsx
- src/components/IssueStats/IssueStats.tsx
- src/components/PrivateDepsWarning/PrivateDepsWarning.i18n/en.json
- src/components/PrivateDepsWarning/PrivateDepsWarning.i18n/index.ts
- src/components/PrivateDepsWarning/PrivateDepsWarning.i18n/ru.json
- src/components/PrivateDepsWarning/PrivateDepsWarning.tsx
- src/utils/db.ts
- trpc/queries/access.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
- trpc/router/project.ts
- trpc/router/search.ts
> Private project: support criteria and dependencies

- src/utils/db.ts
> Drop unused criteria field and these reference in components

- package-lock.json
- package.json
- src/components/Badge.tsx
- src/components/ColorizedMenuItem.tsx
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalBadge.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalDependencyList.tsx
- src/components/GoalList.tsx
- src/components/State.tsx
- src/components/StateDot.tsx
- src/components/StateSwitch.tsx
- src/components/StateWrapper.tsx
> Remove color-layer from runtime

- src/components/ThemeSetter.tsx
- src/pages/_app.tsx
Resolve #1211 
https://github.com/taskany-inc/issues/assets/95316053/d42ab2b5-4a11-46d5-9b6b-06c3a413be4d
https://github.com/taskany-inc/issues/assets/95316053/ed155d5c-7b38-49f6-abcb-b8f8ac8ee96d
> Save user theme on login to db

- package-lock.json
- package.json
- src/components/CommentForm/CommentForm.tsx
Resolve #2132 
https://github.com/taskany-inc/issues/assets/95316053/d31673b8-db6d-4548-b973-297f7c61e941
> File upload: entity too large

- src/components/DashboardPage/DashboardPage.tsx
- src/components/FlatGoalList.tsx
- src/components/GoalListItem.tsx
- src/components/ProjectListItemConnected.tsx
- src/components/Table.tsx
> UserGroup over comments count

- src/components/StateDropdown.tsx
> Data error not on data picker

- prisma/migrations/20231225113714_job_force_runs/migration.sql
- prisma/schema.prisma
- src/utils/worker/index.ts
> Worker improvements

- prisma/seed.ts
- src/utils/worker/goalPingJob.ts
- src/utils/worker/resolve.ts
> Taskany Bot incorrect logic

- .eslintrc.js
- package-lock.json
- package.json
- src/components/ColorizedFilterDropdown.tsx
- src/components/Estimate/Estimate.tsx
- src/components/GoalForm/GoalFormEstimate.tsx
- src/components/GoalPreview/GoalPreviewProvider.tsx
- src/components/ProjectFilter.tsx
- src/components/TagFilter.tsx
- src/hooks/useGoalResource.ts
- src/pages/api/upload.ts
- src/types/date.ts
- src/types/estimate.ts
- src/types/ssrProps.ts
- src/utils/dateTime.ts
- trpc/queries/project.ts
> Prefer interface over type alias

- prisma/migrations/20231219143345_drop_unused_criteria_fields/migration.sql
- prisma/schema.prisma
>  Drop unused criteria field and these reference in components

- src/utils/prepareRecipients.ts
- src/utils/worker/create.ts
- trpc/router/goal.ts
- trpc/router/project.ts
> [email] Recipient is undefined

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
> Fix table width

- cypress/plugins/db.ts
- src/types/history.ts
- src/utils/db/calculatedGoalsFields.ts
- src/utils/db/createComment.ts
- src/utils/db/index.ts
- src/utils/db/updateProjectUpdatedAt.ts
- src/utils/worker/create.ts
- src/utils/worker/goalPingJob.ts
- src/utils/worker/index.ts
- src/utils/worker/resolve.ts
- trpc/access/accessCheckers.ts
- trpc/queries/goals.ts
- trpc/router/goal.ts
- trpc/router/project.ts
- trpc/router/search.ts
> GoalPingJob: remove setInterval

- src/components/GoalCriteriaSuggest.tsx
- src/components/GoalSidebar/GoalSidebar.tsx
Resolve #2172 
In current goal's feed try adding an any goal as criteria
In current goal's sidebar try link current goal with any self-owned goal
> fix(GoalCriteriaSuggest): correct restrict search for suggest

- src/utils/dateTime.test.ts
- src/utils/worker/mail/templates.ts
> Fix list of available years

- package-lock.json
- package.json
- src/components/AccessUserDeleteErrorModal/AccessUserDeleteErrorModal.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.i18n/ru.json
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
Resolve #2174 
Related https://github.com/taskany-inc/bricks/pull/701
> Add view prop to styled tips

- trpc/router/project.ts
Resolve #2202 
https://github.com/taskany-inc/issues/assets/95316053/ba50a339-3b21-447c-b1b6-df4456613419
> support filter nested goals

- package-lock.json
- package.json
> Support MS hotkeys

- src/components/GoalCriteria/GoalCriteria.tsx
Resolve #2205 
in GoalPreview 
in GoalPage
> Goal criteria are too narrow

- src/components/SettingsContent.tsx
> Fix space between RotatableTip & SettingsContent

- src/utils/worker/index.ts
> Remove worker jobs duplicate

- src/utils/worker/mail/templates.ts
- trpc/router/goal.ts
> Estimate update email is bad

- package-lock.json
- package.json
- src/components/DashboardPage/DashboardPage.tsx
- src/components/FilterPopup/FilterPopup.tsx
- src/components/FlatGoalList.tsx
- src/components/GlobalSearch/GlobalSearch.tsx
- src/components/GoalTableList/GoalTableList.tsx
- src/components/GroupedGoalList.tsx
- src/components/ProjectPage/ProjectPage.tsx
Resolve #914
https://github.com/taskany-inc/issues/assets/9020793/2921a2cb-d8b8-4b84-8522-083a19606dca
>  Keyboard navigation in goals list

- src/components/GoalListItem/GoalListItem.module.css
- src/components/GoalListItem/GoalListItem.tsx
- src/components/GoalTableList/GoalTableList.tsx
Resolve #2251 
https://github.com/taskany-inc/issues/assets/9020793/2ccfb375-a4e6-45e4-a1cf-5fb6c38032d2
> Fix GoalListItem hover on keyboard navigation

- package-lock.json
- package.json
Resolve #2253 
https://github.com/taskany-inc/issues/assets/9020793/cf674546-111e-4dce-917f-b7b24af01f6f
> Error on Enter press after applied filters

- package-lock.json
- package.json
> Update bricks package

- package-lock.json
- package.json
> Fix avatars in GoalListItem 

- src/hooks/usePageLoad.ts
- src/pages/_app.tsx
> Custom page progress component

- package-lock.json
- package.json
- src/components/FilterCheckbox.tsx
- src/components/PriorityFilter.tsx
- src/components/ProjectFilter.tsx
- src/components/StateFilter.tsx
- src/components/TagFilter.tsx
- src/components/UserFilter/UserFilter.tsx
Resolve #2246 
https://github.com/taskany-inc/issues/assets/9020793/853df313-ada2-4223-ab3d-a4a716a0e7b8
> AutoComplete enable keypress navigation [integration]

- package-lock.json
- package.json
- src/components/AddInlineTrigger.tsx
Resolve #2274 
https://github.com/taskany-inc/issues/assets/95316053/d3381709-a0a0-4a21-8349-547fe1d94bb7
> Remove focus prop from DOM Node

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
> Harmony: ProjectListItem

- src/components/Page/Page.tsx
- src/pages/_document.tsx
Resolve #2281
https://github.com/taskany-inc/issues/assets/9020793/d92a6ccb-2369-46b8-947d-961dbaeba17c
> Remove loading themePlaceholder.css

- package-lock.json
- package.json
- src/hooks/useMarkdown.tsx
Resolve #2198 
```
https://www.youtube.com/watch?v=dQw4w9WgXcQ
Some text around ...https://www.youtube.com/watch?v=dQw4w9WgXcQ... (link)
links in list
- [md literal link](https://github.com/syntax-tree/unist)
- text before link https://github.com/syntax-tree/unist
- https://github.com/syntax-tree/unist text after link
- https://github.com/syntax-tree/unist and https://github.com/syntax-tree/unist
- https://github.com/syntax-tree/unist, https://github.com/syntax-tree/unist and https://github.com/syntax-tree/unist and etc.
```
> MD: parse urls in plain text

- src/components/Page/Page.tsx
Resolve #2300 
https://github.com/taskany-inc/issues/assets/9020793/3fb60f9c-dd9d-4806-99f1-6c4053879432
> Theme blinking 

- prisma/migrations/20240207173340_/migration.sql
- prisma/schema.prisma
Resolve #2305
Related issues #2235
_Please replace this line with instructions on how to test your changes, a note on the devices and browsers this has been tested on, as well as any relevant images for UI changes._
> New state colors model 

- src/pages/_app.css
> Global font-size

- cypress/fixtures/langs.json
- package-lock.json
- package.json
- src/components/OfflineBanner/OfflineBanner.i18n/en.json
- src/components/OfflineBanner/OfflineBanner.i18n/index.ts
- src/components/OfflineBanner/OfflineBanner.i18n/ru.json
- src/components/OfflineBanner/OfflineBanner.tsx
- src/components/Page/Page.tsx
- src/pages/api/health.tsx
> Offline bar from bricks

- package-lock.json
- package.json
- src/components/GoalListItem/GoalListItem.module.css
- src/components/ScrollableView.tsx
Resolve #2284 
https://github.com/taskany-inc/issues/assets/95316053/9bf7cbc6-8f80-42db-9388-18a8d39df8bd
https://github.com/taskany-inc/issues/assets/95316053/2d8cee6a-84dd-459a-ab8f-0d5addc27451
> GoalListItem should have a shadow in the light theme

- src/components/CommentForm/CommentForm.module.css
- src/components/CommentForm/CommentForm.tsx
- src/components/GoalActivityFeed.tsx
- src/utils/db/createComment.ts
> Allow goal participants to update status

- package-lock.json
- src/components/PageHeader/PageHeader.i18n/en.json
- src/components/PageHeader/PageHeader.i18n/ru.json
- src/components/PageHeader/PageHeader.tsx
> Return dashboard link in nav menu

- .eslintrc.js
- src/components/PageTitle.tsx
> ESLint: enable jsx-curly-brace-presence

- src/components/DashboardPage/DashboardPage.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
- src/components/ProjectTeamPage/ProjectTeamPage.tsx
> Remove TreeView from bricks usage

- package-lock.json
- package.json
- src/components/OfflineBanner/OfflineBanner.tsx
> Update offline banner from bricks

- src/components/FilterAutoCompleteInput/FilterAutoCompleteInput.tsx
> Do not autofocus search input after navigation

- prisma/migrations/20240221092641_app_config/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- src/components/Page/Page.tsx
- src/pages/_app.tsx
- src/utils/db/index.ts
- src/utils/declareSsrProps.ts
> Custom logo via plugins

- src/components/GoalTableList/GoalTableList.tsx
- src/components/NewGoalCriteria/NewGoalCriteria.tsx
Resolve #2380 
https://github.com/taskany-inc/issues/assets/95316053/42b978e4-b4f9-4fd4-a817-be139d446f94
> GoalPreview should open when clicked in an empty area inside GoalListItem

- src/components/ProjectTeamPage/ProjectTeamPage.tsx
- src/components/TeamListItem.tsx
- src/components/TeamMemberListItem/TeamMemberListItem.tsx
- trpc/router/crew.ts
> Add unit total to team resources

- src/components/CriteriaForm/CriteriaForm.tsx
> Allow edit criteria title

- src/components/Page/Page.tsx
- src/utils/db/index.ts
- src/utils/declareSsrProps.ts
- trpc/router/appConfig.ts
- trpc/router/index.ts
Resolve #2392 
https://github.com/taskany-inc/issues/assets/9020793/2c0e01d4-207b-4b17-8ab2-732b70d286b4
> get appConfig in <Head /> component

- src/components/CardHeader/CardHeader.module.css
- src/components/CardHeader/CardHeader.tsx
- src/components/CommentView/CommentView.module.css
- src/components/CommentView/CommentView.tsx
- src/components/GoalContentHeader/GoalContentHeader.module.css
- src/components/GoalContentHeader/GoalContentHeader.tsx
- src/components/GoalPreview/GoalPreview.module.css
- src/components/GoalPreview/GoalPreview.tsx
> Bring new background colors to Goal preview

- src/components/CriteriaForm/CriteriaForm.i18n/en.json
- src/components/CriteriaForm/CriteriaForm.i18n/ru.json
- src/components/CriteriaForm/CriteriaForm.module.css
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalCriteriaSuggest.tsx
Add reset form button
Also criteria form will reset after submit
Resolve #2345 
https://github.com/taskany-inc/issues/assets/7002692/3fde8ae2-96ad-4649-b28f-f67eabe1c05d
> Criteria input should be cleared after submit

- src/components/GoalTableList/GoalTableList.module.css
- src/components/GoalTableList/GoalTableList.tsx
- src/components/TableListItem/TableListItem.module.css
> Primary color for title of selected goal list item

- trpc/router/crew.ts
> Fix http method of get crew group list

- cypress/e2e/projectSettings.cy.ts
- package-lock.json
- package.json
- src/components/CommonHeader.tsx
- src/components/ExplorePageLayout/ExplorePageLayout.tsx
- src/components/ExploreProjectsPage/ExploreProjectsPage.tsx
- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/components/FilteredPage/FilteredPage.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/components/ProjectPageTabs/ProjectPageTabs.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/ProjectTeamPage/ProjectTeamPage.tsx
- src/components/UserSettingsPage/UserSettingsPage.tsx
- src/utils/domObjects.ts
> Project Page Tabs

- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e.yml
- .github/workflows/pr.yml
- .github/workflows/publish.yml
- next.config.js
- package-lock.json
- package.json
> Ignore sentry warnings during build

- src/components/PageHeader/PageHeader.module.css
Resolve #2435 
https://github.com/taskany-inc/issues/assets/95316053/5531845a-e92f-4852-ba05-833fd9a9ed20
> GlobalSearch shifts layout on smaller screens

- package-lock.json
- package.json
- src/components/CommentView/CommentView.module.css
> Return border on light theme

- src/components/CommentCreateForm/CommentCreateForm.tsx
Resolve #2444 
https://github.com/taskany-inc/issues/assets/95316053/e9e51c02-286c-46f8-b90d-61c9d109b1d7
> Update State Button doesn't work

- package-lock.json
- package.json
- tsconfig.json
> Install typescript plugin for css modules

- src/components/HistoryRecord/HistoryRecord.i18n/en.json
- src/components/HistoryRecord/HistoryRecord.i18n/ru.json
- src/components/HistoryRecord/HistoryRecord.tsx
> Collapsed comments markup problem

- src/hooks/useMarkdown.tsx
> MD cuts non-empty line breaks

- src/components/CommonHeader.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/PageUserMenu.tsx
Resolve: #2458 
Related issues #2349
> Navigation Sidebar: Header UserMenu

- src/schema/goal.ts
Resolve #2496 
https://github.com/taskany-inc/issues/assets/9020793/60ab6682-e54e-4a9d-be50-da2a08baee57
> Goal edit form doesn't submit

- src/components/AppliedTagFilter/AppliedTagFilter.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- trpc/router/tag.ts
> Show applied tags filters

- src/components/NavigationSidebar/NavigationSidebar.module.css
- src/components/PageNavigation/PageNavigation.tsx
- src/utils/declareSsrProps.ts
- trpc/router/project.ts
Resolve #2463 
Related issues #2349 
https://github.com/taskany-inc/issues/assets/9020793/fd2649e9-f8c8-49ae-bdc9-0f39edca0e5c
> Navigation Sidebar: My projects

- src/components/GoalsPage/GoalsPage.tsx
- src/components/PageNavigation/PageNavigation.i18n/en.json
- src/components/PageNavigation/PageNavigation.i18n/ru.json
- src/components/PageNavigation/PageNavigation.tsx
- src/hooks/router.ts
- src/pages/goals/starred.tsx
- src/pages/goals/watching.tsx
- src/schema/common.ts
- src/utils/declareGoalsSsrProps.ts
- trpc/router/goal.ts
Resolve #2461 
Related issues #2349 
https://github.com/taskany-inc/issues/assets/9020793/265dd0d6-a637-4fda-af71-60922836f5c7
>  Navigation Sidebar: Starred and Watched goals

- src/components/GoalHeader/GoalHeader.tsx
- src/components/StateFilter.tsx
- src/components/StateSwitch.tsx
- src/components/StateWrapper.tsx
- src/hooks/useUrlFilterParams.ts
- trpc/inferredTypes.ts
Resolve #2511 
Related issue: 
- https://github.com/taskany-inc/issues/pull/2490
> Replace StateType from @prisma/client to local type

- src/utils/auth.ts
> Do not send emails to the author of the goal

- src/components/GoalCriteria/GoalCriteria.module.css
- src/components/GoalCriteria/GoalCriteria.tsx
Resolve #2520 
Correct popup position:
hidden edit actions
> Hide criteria action for not editable user and edit form positioning

- src/components/GoalActivityFeed/GoalActivityFeed.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
> Criteria as goal converts to simple criteria by edit

- src/components/GoalBadge.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalTableList/GoalTableList.tsx
- src/components/IssueParent/IssueParent.tsx
- src/components/IssueTitle.tsx
- src/components/NextLink.tsx
- src/components/ProjectBadge.tsx
Also restore correct behavior for parent links in goal header and new goal criteria
Resolve #2485
> The language is reset when clicking on the project/goal link from goal header

- src/components/DashboardPage/DashboardPage.tsx
> Load more button should be disabled on fetching

- cypress/e2e/projects.cy.ts
- src/components/DashboardPage/DashboardPage.tsx
- src/components/GoalTableList/GoalTableList.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/utils/domObjects.ts
- trpc/inferredTypes.ts
- trpc/router/project.ts
Resolve #2515 
https://github.com/taskany-inc/issues/assets/9020793/bc9398b1-358d-45f5-a99c-ecd64486f328
>  Dashboard request optimization

- src/components/ExploreProjectsPage/ExploreProjectsPage.tsx
- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/components/ProjectListItem/ProjectListItem.module.css
- src/components/ProjectListItem/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/components/ProjectSubscriptionButtons.tsx
- src/components/StarButton/StarButton.tsx
- src/components/TableRowItem/TableRowItem.module.css
- src/components/WatchButton/WatchButton.tsx
Resolve #2413 
https://github.com/taskany-inc/issues/assets/9020793/fb616a46-7c09-40be-8635-e8a4eeb026be
> Return watch and star buttons

- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalCriteriaSuggest.tsx
- src/components/GoalSelect.tsx
- trpc/router/goal.ts
Fixed some bugs belong after refactoring
- not worked suggest feature
- strange criteria update work
- refetching current criteria list
Resolve #2499
> Goal suggestions doesn't work when editing criteria

- src/components/GoalCreateForm/GoalCreateForm.i18n/en.json
- src/components/GoalCreateForm/GoalCreateForm.i18n/ru.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/NotificationsHub/NotificationsHub.tsx
- src/hooks/useGoalResource.ts
- src/utils/dispatchNotification.ts
- src/utils/notifyPromise.ts
- trpc/router/goal.ts
Now in case when user will trying create goal into archived project then get an error
Also if these project contains in user's LocalStorage then this project will be remove
Resolve #2524
> Goals can be created in archived project

- package-lock.json
- package.json
Resolve #2549 
Related issues #2548
> Fix GoalTableList item

- trpc/queries/project.ts
- trpc/router/project.ts
- trpc/router/search.ts
> Global search can find archived project

- package-lock.json
- package.json
- src/components/EstimateDropdown/EstimateDropdown.tsx
- src/types/date.ts
> Return aliases to estimate filter

- src/components/StarButton/StarButton.tsx
> fix History changes counter

- src/components/CommentView/CommentView.module.css
- src/components/CommentView/CommentView.tsx
- src/components/GoalActivityFeed/GoalActivityFeed.module.css
- src/components/GoalActivityFeed/GoalActivityFeed.tsx
> Fix comment margins

- src/components/GoalContentHeader/GoalContentHeader.module.css
- src/components/GoalContentHeader/GoalContentHeader.tsx
- src/components/GoalPage/GoalPage.module.css
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalPreview/GoalPreview.module.css
- src/components/GoalPreview/GoalPreview.tsx
- src/components/GoalTableList/GoalTableList.module.css
- src/components/HistoryRecord/HistoryRecord.module.css
- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/RelativeTime/RelativeTime.module.css
Resolve #2599 
https://github.com/taskany-inc/issues/assets/9020793/c123dae6-c39a-418c-b329-c637271a497a
> blinking color in comment time

- src/components/AccessUserDeleteErrorModal/AccessUserDeleteErrorModal.module.css
- src/components/AccessUserDeleteErrorModal/AccessUserDeleteErrorModal.tsx
- src/components/CriteriaForm/CriteriaForm.module.css
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalCriteria/GoalCriteria.module.css
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/IssueKey/IssueKey.module.css
- src/components/IssueKey/IssueKey.tsx
- src/components/Page/Page.tsx
- src/components/RotatableTip/RotatableTip.module.css
- src/components/RotatableTip/RotatableTip.tsx
- src/components/Theme.tsx
> Do not use JS constants from colors Pt.2

- src/components/FiltersPanel/FiltersPanel.i18n/en.json
- src/components/FiltersPanel/FiltersPanel.i18n/ru.json
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/SortButton/SortButton.tsx
- src/hooks/useUrlFilterParams.ts
- trpc/router/goal.ts
Resolve #2601 
https://github.com/taskany-inc/issues/assets/9020793/a35f97df-9f2f-4a94-9c7b-828c8a58ca13
> Return sorting to filters bar

- src/components/WhatsNewLayout.tsx
> Wrong text color on "What's new"

- src/components/UserSettingsPage/UserSettingsPage.i18n/en.json
- src/components/UserSettingsPage/UserSettingsPage.i18n/ru.json
- src/components/UserSettingsPage/UserSettingsPage.tsx
> Not all of user settings i18ned

- src/hooks/useMarkdown.tsx
> Unexpected <p> in Md component

- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalPage/GoalPage.tsx
- src/components/GoalParentComboBox.tsx
- src/components/GoalParentDropdown/GoalParentDropdown.tsx
- src/components/Page/Page.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/hooks/useProjectResource.ts
Resolve #2534 
Related issues #2558
> Prevent unexpected project cache in Localstorage

- src/components/SettingsContent/SettingsContent.tsx
> Return paddings to settings cards

- trpc/router/project.ts
Resolve #2627 
https://github.com/taskany-inc/issues/assets/9020793/32ace8e1-c965-4076-93cb-7b7f40e05939
> sorting at Dashboard page

- package-lock.json
- package.json
- src/components/AccessUserDeleteErrorModal/AccessUserDeleteErrorModal.module.css
- src/components/AccessUserDeleteErrorModal/AccessUserDeleteErrorModal.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/RotatableTip/RotatableTip.tsx
> Harmony: Tips

- src/components/HistoryRecord/HistoryRecord.i18n/en.json
- src/components/HistoryRecord/HistoryRecord.i18n/ru.json
- src/components/HistoryRecord/HistoryRecord.tsx
> Missing translation in history item counters

- src/components/ActivityFeed/ActivityFeed.module.css
- src/components/GoalContentHeader/GoalContentHeader.module.css
- src/components/GoalContentHeader/GoalContentHeader.tsx
> Fix GoalActivityFeed layout

- src/utils/db/calculatedGoalsFields.ts
> Participants have read only rights on goals

- src/components/GoalPreview/GoalPreview.tsx
> Goal criteria click in sidebar does nothing

- package-lock.json
- package.json
- src/components/CommentView/CommentView.tsx
- src/components/GoalParentComboBox.tsx
- src/components/HistoryRecord/HistoryRecord.tsx
- src/components/NavigationSidebar/NavigationSidebar.module.css
- src/components/NavigationSidebar/NavigationSidebar.tsx
> Fix hydration error at goal page

- src/pages/api/trpc/[trpc].ts
> Global replacing 500 error

- cypress/fixtures/langs.json
- package.json
- src/components/CriteriaForm/CriteriaForm.tsx
- src/hooks/useGoalResource.ts
- src/pages/api/trpc/[trpc].ts
- src/utils/declareSsrProps.ts
- trpc/access/access.i18n/en.json
- trpc/access/access.i18n/index.ts
- trpc/access/access.i18n/ru.json
- trpc/access/accessCheckers.ts
- trpc/access/accessEntityGetters.ts
- trpc/access/accessMiddlewares.ts
- trpc/router/filter.ts
- trpc/router/goal.ts
- trpc/router/router.i18n/en.json
- trpc/router/router.i18n/index.ts
- trpc/router/router.i18n/ru.json
> i18n in backend responses

- src/components/GoalParentComboBox.tsx
Resolve #2656 
https://github.com/taskany-inc/issues/assets/95316053/f47b911d-b012-4cc5-b011-3b0184116864
> Can't click to project when transfering goal

- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/pages/explore/projects.tsx
- src/pages/explore/top.tsx
Resolve #2667 
https://github.com/taskany-inc/issues/assets/9020793/67215451-0296-4edf-8727-f6a243bf4f36
> Top and Project are referred to the same page

- src/components/AppliedTagFilter/AppliedTagFilter.tsx
- src/components/TagDropdown/TagDropdown.tsx
- trpc/queries/tag.ts
- trpc/router/tag.ts
> Fix querying tags in filter

- package-lock.json
- package.json
- src/components/GoalCriteria/GoalCriteria.tsx
- trpc/queries/criteria.ts
- trpc/router/goal.ts
Also apply same ordering rules for linked criteria for specific goal
Resolve #2675
> Fix order criteria in goal lists

- src/components/FiltersBar/FiltersBar.tsx
> Fix warning from DropdownTrigger

- package-lock.json
- package.json
- src/components/CommentView/CommentView.tsx
- src/components/SettingsContent/SettingsContent.module.css
- src/components/SettingsContent/SettingsContent.tsx
> Update SettingsCard from harmony

- src/components/HotkeysModal/HotkeysModal.tsx
- src/components/RotatableTip/RotatableTip.tsx
- src/components/UserInviteForm/UserInviteForm.tsx
> Keyboard from @bricks/harmony

- src/components/FilterDeleteForm/FilterDeleteForm.tsx
- src/components/GoalDeleteModal/GoalDeleteModal.tsx
- src/components/KeyInput/KeyInput.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
> Text from @bricks/harmony

- package-lock.json
- src/components/KeyInput/KeyInput.tsx
- src/utils/domObjects.ts
> KeyInput to harmony components

- src/components/Reactions/Reactions.tsx
> Popup from @bricks/harmony

- src/utils/getUserName.ts
> safeUserData shout return name before than nickname

- package-lock.json
- package.json
- src/components/AccessUserDeleteErrorModal/AccessUserDeleteErrorModal.tsx
- src/components/FeedbackCreateForm/FeedbackCreateForm.tsx
- src/components/FilterCreateForm/FilterCreateForm.tsx
- src/components/FilterDeleteForm/FilterDeleteForm.module.css
- src/components/FilterDeleteForm/FilterDeleteForm.tsx
- src/components/GoalDeleteModal/GoalDeleteModal.module.css
- src/components/GoalDeleteModal/GoalDeleteModal.tsx
- src/components/GoalPreview/GoalPreview.module.css
- src/components/GoalPreview/GoalPreview.tsx
- src/components/HotkeysModal/HotkeysModal.tsx
- src/components/ImageFullScreen/ImageFullScreen.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.module.css
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/ProjectSwitchPublicConfirmModal/ProjectSwitchPublicConfirmModal.tsx
- src/components/UserInviteForm/UserInviteForm.tsx
- src/components/WhatsNew/WhatsNew.tsx
> Modal from @bricks/harmony

- package-lock.json
- src/components/CommentForm/CommentForm.tsx
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/FeedbackCreateForm/FeedbackCreateForm.tsx
- src/components/FilterCreateForm/FilterCreateForm.tsx
- src/components/FilterDeleteForm/FilterDeleteForm.tsx
- src/components/FiltersBar/FiltersBar.tsx
- src/components/FormActions/FormActions.module.css
- src/components/FormActions/FormActions.tsx
- src/components/GoalCreateForm/GoalCreateForm.module.css
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalDeleteModal/GoalDeleteModal.tsx
- src/components/GoalEditForm/GoalEditForm.module.css
- src/components/GoalEditForm/GoalEditForm.tsx
- src/components/GoalForm/GoalForm.module.css
- src/components/GoalForm/GoalForm.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.module.css
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.module.css
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/UserInviteForm/UserInviteForm.tsx
- src/components/UserSettingsPage/UserSettingsPage.module.css
- src/components/UserSettingsPage/UserSettingsPage.tsx
> Replace Form elements

- package-lock.json
- package.json
- src/components/GoalContentHeader/GoalContentHeader.module.css
- src/components/GoalContentHeader/GoalContentHeader.tsx
- src/components/GoalListItemCompact/GoalListItemCompact.tsx
- src/components/ProjectAccessUser/ProjectAccessUser.tsx
- src/components/ProjectListItem/ProjectListItem.tsx
- src/components/ProjectParticipants/ProjectParticipants.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/UserSettingsPage/UserSettingsPage.tsx
> Update Fieldset from @bricks/harmony

- package-lock.json
- package.json
- src/components/DashboardPage/DashboardPage.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/FlatGoalList.tsx
- src/components/GlobalSearch/GlobalSearch.tsx
- src/components/GoalParentComboBox.tsx
- src/components/GoalTableList/GoalTableList.tsx
- src/components/GroupedGoalList.tsx
- src/components/Md.tsx
- src/components/NavigationSidebar/NavigationSidebar.tsx
- src/components/PageFooter/PageFooter.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/components/UserComboBox.tsx
- src/components/WhatsNewLayout.tsx
- src/hooks/usePageLoad.ts
- src/pages/_app.tsx
Resolve #2703 
https://github.com/taskany-inc/issues/assets/9020793/2e48bbd1-8f23-4028-93d7-85743868579e
> Md, PageLoadProgress, ListView and Footer from harmony

- cypress/e2e/goalDependencies.cy.ts
- src/components/GoalDependency/GoalDependency.module.css
- src/components/GoalDependency/GoalDependency.tsx
- src/utils/domObjects.ts
Resolve #2705 
https://github.com/taskany-inc/issues/assets/9020793/a9a6e0b0-4ecc-4a8e-bcf2-e23a6a85a72f
> Replace AutoCompleteRadioGroup with a Switch

- package-lock.json
- package.json
> Update @taskany/bricks version

- src/components/AppliedUsersFilter/AppliedUsersFilter.tsx
- src/components/UserDropdown/UserDropdown.tsx
- src/hooks/useUserResource.ts
- src/types/crew.ts
- trpc/router/crew.ts
- trpc/router/user.ts
> Lookup crew users by default

- package-lock.json
- package.json
- src/components/Md.tsx
- src/components/WhatsNewLayout.tsx
- src/hooks/useMarkdown.tsx
> Fix markdown

- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
> Show name of selected User on Transfer modal

- src/components/EstimateDropdown/EstimateDropdown.tsx
- src/components/GoalForm/GoalForm.tsx
- trpc/queries/projectV2.ts
Resolve #2721 
https://github.com/taskany-inc/issues/assets/9020793/86042db3-6dd0-4ead-b206-a32f4f81eed6
https://github.com/taskany-inc/issues/assets/9020793/05759613-e956-4661-b6dc-095fe3eade05
> Goals form state update problem

- src/components/Dropdown/Dropdown.i18n/en.json
- src/components/Dropdown/Dropdown.i18n/ru.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalForm/GoalForm.tsx
- src/components/GoalParentDropdown/GoalParentDropdown.tsx
- src/components/PageNavigation/PageNavigation.tsx
- src/components/ProjectContext/ProjectContext.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.i18n/en.json
- src/components/ProjectCreateForm/ProjectCreateForm.i18n/ru.json
- src/components/ProjectCreateForm/ProjectCreateForm.module.css
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
- src/components/ProjectTeamPage/ProjectTeamPage.tsx
- src/pages/projects/[id]/index.tsx
- src/schema/project.ts
- src/utils/declareSsrProps.ts
- trpc/queries/projectV2.ts
- trpc/router/project.ts
- trpc/router/projectV2.ts
Resolve #2702 
https://github.com/taskany-inc/issues/assets/9020793/9e77cfc1-a5da-4af6-8cfc-328d2470c2ce
https://github.com/taskany-inc/issues/assets/9020793/631c8e42-cb77-40e6-a80a-1613339bff38
> Project create - parent option

- src/utils/declareGoalsSsrProps.ts
- trpc/router/project.ts
> FirstLevel params doesn't work (again)

- cypress/e2e/projects.cy.ts
- src/components/DashboardPage/DashboardPage.tsx
- src/components/ExploreProjectsPage/ExploreProjectsPage.tsx
- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
- src/components/ProjectListItem/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/pages/index.tsx
- src/utils/dateTime.ts
- src/utils/recalculateCriteriaScore.ts
- src/utils/transformer.ts
- trpc/inferredTypes.ts
- trpc/queries/criteria.ts
- trpc/queries/filter.ts
- trpc/queries/flow.ts
- trpc/queries/goalV2.ts
- trpc/queries/project.ts
- trpc/queries/projectV2.ts
- trpc/router/filter.ts
- trpc/router/project.ts
- trpc/router/projectV2.ts
- trpc/utils.ts
Use kysely query for dashboard instead of prisma
Resolve #2653
> Rewrite Dashboard query with kysely provider

- trpc/queries/projectV2.ts
> Filter by dates works incorrectly in Dashboard

- src/components/FormControlEditor/FormControlEditor.tsx
> Markdown user autocomplete: items duplicates

- src/components/EstimateDropdown/EstimateDropdown.tsx
> fix(EstimateDropdown): calculate estimate value

- package-lock.json
- package.json
> Character in user badge should be centered

- src/components/CommentCreateForm/CommentCreateForm.i18n/en.json
- src/components/CommentCreateForm/CommentCreateForm.i18n/ru.json
- src/components/CommentCreateForm/CommentCreateForm.tsx
- src/components/CommentForm/CommentForm.tsx
> Validation with visible error in comment

- src/utils/db/types.ts
- trpc/router/user.ts
> Crew user may have `login: null`

- src/utils/worker/mail/templates.ts
> Emails texts

- package-lock.json
- package.json
> Line start is unclikable

- src/utils/db/crewIntegration.ts
- src/utils/worker/tsconfig.json
> Worker build doesn't fail

- src/components/CommentView/CommentView.tsx
> Disable edit comment on double-click

- trpc/queries/projectV2.ts
- trpc/router/project.ts
> Show partnership project goals

- src/components/ExploreProjectsStarredPage/ExploreProjectsStarredPage.i18n/en.json
- src/components/ExploreProjectsStarredPage/ExploreProjectsStarredPage.i18n/ru.json
- src/components/ExploreProjectsStarredPage/ExploreProjectsStarredPage.module.css
- src/components/ExploreProjectsStarredPage/ExploreProjectsStarredPage.tsx
- trpc/router/projectV2.ts
> fix(StarredProjects): fix empty list

- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/pages/projects/[id]/index.tsx
> Project Create Form: flow doesn't loaded

- src/components/GoalParentDropdown/GoalParentDropdown.tsx
- src/schema/project.ts
- src/utils/filters.ts
- trpc/queries/projectV2.ts
- trpc/router/project.ts
- trpc/router/projectV2.ts
> Project suggestions: fix priority

- package-lock.json
- package.json
- src/components/GoalTableList/GoalTableList.module.css
- src/components/GoalTableList/GoalTableList.tsx
> Wrap goal's owner name into ellipsis container in goal list item

- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalSidebar/GoalSidebar.i18n/en.json
- src/components/GoalSidebar/GoalSidebar.i18n/ru.json
- src/components/GoalSidebar/GoalSidebar.tsx
- src/utils/dispatchModal.ts
By click on `Clone goal` control will open goal create form with prefilled fields, ex. title, description, project, priority, tags
Resolve #2790
> Clone goal

- .github/workflows/e2e.yml
- package-lock.json
- package.json
- src/components/DashboardPage/DashboardPage.tsx
- src/components/EstimateDropdown/EstimateDropdown.tsx
- src/components/FiltersBar/FiltersBar.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/FlatGoalList.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalTableList/GoalTableList.tsx
- src/components/GoalsKanbanCard/GoalsKanbanCard.module.css
- src/components/GoalsKanbanCard/GoalsKanbanCard.tsx
- src/components/GoalsPage/GoalsPage.tsx
- src/components/GroupedGoalList.tsx
- src/components/IssueStats/IssueStats.tsx
- src/components/Kanban/Kanban.module.css
- src/components/Kanban/Kanban.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.module.css
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/hooks/router.ts
- src/hooks/useUrlFilterParams.ts
- src/utils/kanban.ts
Resolve #2766
https://github.com/user-attachments/assets/303fb45b-cff9-4280-9be3-9c5dd12ebd93
> Canban mode

- src/hooks/useUrlFilterParams.ts
Resolve #2870 
https://github.com/user-attachments/assets/96c64e54-4bbd-4f3a-a20c-2af5bd2e8eed
> View props cleared on first filter added

- cypress/fixtures/langs.json
- src/components/GlobalSearch/GlobalSearch.i18n/en.json
- src/components/GlobalSearch/GlobalSearch.i18n/ru.json
- src/components/GlobalSearch/GlobalSearch.module.css
- src/components/GlobalSearch/GlobalSearch.tsx
> Search no results message

- src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
> Change buttons to icons on top project page

- src/components/DashboardPage/DashboardPage.tsx
- src/components/ProjectListItemConnected.tsx
> Mark goals from other (partnership) projects

- src/components/GroupedGoalList.tsx
- src/components/ProjectListItemConnected.tsx
> ProjectSubscriptionButtons: icons view cases

- src/components/DashboardPage/DashboardPage.tsx
> No Goals Padding

- src/components/TableRowItem/TableRowItem.module.css
Resolve #2899
**BEFORE**
**AFTER**
> List item hover from new colors palet

- package-lock.json
- package.json
- src/components/GoalActivityFeed/GoalActivityFeed.tsx
- src/components/PageNavigation/PageNavigation.module.css
- src/components/PageNavigation/PageNavigation.tsx
Resolve #2901 
https://github.com/user-attachments/assets/711b05dd-f0e3-434d-83fe-5bea05a766c4
> Fix forwardRef warning

- src/schema/goal.ts
- src/schema/schema.i18n/en.json
- src/schema/schema.i18n/ru.json
> Reduce min goal title to 6 symbols

- src/components/GoalTableList/GoalTableList.tsx
- src/components/UserBadge/UserBadge.tsx
Resolve #2855 
https://github.com/user-attachments/assets/87add97c-acb8-40f8-b444-7e5e64dd2f34
>  Add Tooltips to Users

- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalActivityFeed/GoalActivityFeed.tsx
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/GoalCriteriaSuggest.tsx
- src/components/GoalSidebar/GoalSidebar.tsx
> CriteriaForm doesn't know the current criteria list by change them

- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected.tsx
- trpc/queries/projectV2.ts
- trpc/router/projectV2.ts
Resolve #2856 
Related issues #2844, #2767
> Rewrite project children list for grouped goals' view

- src/components/GoalSidebar/GoalSidebar.tsx
- src/utils/db/index.ts
- trpc/router/goal.ts
- trpc/router/router.i18n/en.json
- trpc/router/router.i18n/ru.json
> Shouldn't allow to add current project as partner

- cypress/fixtures/langs.json
- src/components/GoalCreateForm/GoalCreateForm.tsx
- src/components/GoalForm/GoalForm.tsx
- src/hooks/useGoalResource.ts
- src/schema/goal.ts
- src/schema/schema.i18n/en.json
- src/schema/schema.i18n/ru.json
- trpc/router/goal.ts
> Null error in state field validation

- package-lock.json
- package.json
> Mentions: fix suggestions z-index

- src/components/GoalCriteria/GoalCriteria.tsx
> Unexpected error by criteria edit

- src/components/ProjectListItemConnected.tsx
> Hide "No goals yet" if the project has child projects

- src/components/GroupedGoalList.tsx
- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
> Icon subscribe buttons to Grouped Page View

- trpc/queries/goalV2.ts
- trpc/router/projectV2.ts
Chages in join condition
Resolve #2937
> Fix 5xx on project's goals query

- package-lock.json
- package.json
- src/components/AppliedEstimateFilter/AppliedEstimateFilter.tsx
- src/components/AppliedGoalParentFilter/AppliedGoalParentFilter.tsx
- src/components/AppliedPriorityFilter/AppliedPriorityFilter.tsx
- src/components/AppliedStateFilter/AppliedStateFilter.tsx
- src/components/AppliedTagFilter/AppliedTagFilter.tsx
- src/components/AppliedUsersFilter/AppliedUsersFilter.tsx
- src/components/CommonHeader.tsx
- src/components/FiltersBar/FiltersBar.module.css
- src/components/FiltersBar/FiltersBar.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/ProjectPage/ProjectPage.tsx
> FilterBar from bricks

- cypress/fixtures/langs.json
- package-lock.json
- src/components/FiltersPanel/FiltersPanel.i18n/en.json
- src/components/FiltersPanel/FiltersPanel.i18n/ru.json
- src/components/FiltersPanel/FiltersPanel.tsx
- src/hooks/useUrlFilterParams.ts
- src/schema/common.ts
- src/utils/db/index.ts
- trpc/queries/goalV2.ts
- trpc/queries/goals.ts
- trpc/queries/project.ts
- trpc/queries/projectV2.ts
- trpc/router/goal.ts
- trpc/router/project.ts
> Add an option to hide criteria goals

- src/components/ProjectListItem/ProjectListItem.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.module.css
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectSubscriptionButtons/ProjectSubscriptionButtons.tsx
> Add "open in a new tab" button next to goal create in tree view

- trpc/queries/goalV2.ts
- trpc/queries/projectV2.ts
Resolve #2974 
Related issues #2908, #2973
> Goals duplicates at paginated list

- cypress/e2e/dashboard.cy.ts
> Remove e2e tests skip

- src/components/BetaLiteral.tsx
- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalActivityFeed/GoalActivityFeed.tsx
Resolve #2976 
Related issues #2484 , #2955, #2964
> Hide external tasks under beta flag

- src/components/GoalActivityFeed/GoalActivityFeed.tsx
>  Fix create criteria with task

- cypress/e2e/projects.cy.ts
> Failing tests in project spec

- generated/kysely/types.ts
- prisma/migrations/20240923113428_append_resolution_fields_for_task_model/migration.sql
- prisma/schema.prisma
- src/utils/db/calculatedGoalsFields.ts
- src/utils/integration/jira.ts
- trpc/queries/external.ts
- trpc/router/goal.ts
- trpc/router/jira.ts
> Use `resolution` jira field for properly determinate of completion the task

- package-lock.json
- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
- src/components/ProjectPage/ProjectPage.tsx
- trpc/queries/projectV2.ts
- trpc/router/projectV2.ts
> Checkbox "empty projects" don't visible on project page

- package-lock.json
- package.json
- src/components/DashboardPage/DashboardPage.tsx
- src/components/Kanban/Kanban.module.css
- src/components/Page/Page.module.css
- src/components/Page/Page.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.module.css
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
- src/components/ProjectPage/ProjectPage.tsx
Resolve #3004 
https://github.com/user-attachments/assets/37c27e75-6dee-485e-b017-d1bf4e5ef2e3
> Sticky Kanban

- src/components/GoalActivityFeed/GoalActivityFeed.tsx
- src/components/GoalCriteria/GoalCriteria.i18n/en.json
- src/components/GoalCriteria/GoalCriteria.i18n/ru.json
- src/components/GoalCriteria/GoalCriteria.tsx
- src/components/NotificationsHub/NotificationsHub.tsx
- src/hooks/useGoalResource.ts
- src/utils/dispatchNotification.ts
- src/utils/notifyPromise.ts
- trpc/queries/external.ts
- trpc/router/goal.ts
- trpc/router/router.i18n/en.json
- trpc/router/router.i18n/ru.json
> Manually updating a linked task

- src/schema/goal.ts
> Cannot create personal goal if personal project does't exists

- src/components/GoalCreateForm/GoalCreateForm.tsx
> Add new goal to current page

- package-lock.json
- src/components/WhatsNew/WhatsNew.tsx
> fix: what's new modal is disappearing after page load

- trpc/access/accessEntityGetters.ts
> Fix project editable access

- src/components/Kanban/Kanban.module.css
- src/components/Kanban/Kanban.tsx
- trpc/queries/goalV2.ts
- trpc/router/projectV2.ts
https://github.com/user-attachments/assets/bc7a1add-0f21-4f70-b1b4-449905a66529
> Drag'n drop: editable props

- src/components/DashboardPage/DashboardPage.tsx
- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
- src/components/ProjectPage/ProjectPage.tsx
- src/pages/projects/[id]/index.tsx
- trpc/queries/projectV2.ts
- trpc/router/projectV2.ts
> Don't hide projects that have goals in nested projects

- src/components/ProjectTeamPage/ProjectTeamPage.tsx
- src/components/TeamComboBox/TeamComboBox.tsx
- trpc/router/projectV2.ts
> Fix team page 500 error

- trpc/queries/filter.ts
> User filter access

- src/components/GoalCreateForm/GoalCreateForm.tsx
> Goals invalidation

- cypress/fixtures/langs.json
- src/components/FiltersPanel/FiltersPanel.i18n/en.json
- src/components/FiltersPanel/FiltersPanel.i18n/ru.json
- src/components/FiltersPanel/FiltersPanel.tsx
> Translations in filters panel don't work

- src/components/CriteriaForm/CriteriaForm.tsx
- src/components/GoalActivityFeed/GoalActivityFeed.tsx
> fix(INTERNAL-1297): drop beta flag for criteria with jira tasks

- trpc/queries/ranking.ts
- trpc/router/goalV2.ts
- trpc/router/projectV2.ts
- trpc/utils.ts
> Organize ranking queries

- src/components/EstimateDropdown/EstimateDropdown.tsx
> Fix recalc translations for `<EstimateDropdown />`

- src/middleware.ts
- src/utils/analyticsEvent.ts
Allow to create custom events using the same API that middleware uses
> Move event processing out of middleware

- src/components/FiltersPanel/FiltersPanel.tsx
> Enable kanban view for all users

- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
- trpc/router/projectV2.ts
> fix(INTERNAL-1354): fix dashboard queries

- src/utils/worker/mail/index.ts
> Flag for mailer

- trpc/router/whatsnew.ts
> Show last written whatsnew

- src/components/WhatsNew/WhatsNew.tsx
- src/utils/trpcClient.ts
- trpc/router/whatsnew.ts
> Whatsnew in separate trpc call

- src/components/OfflineBanner/OfflineBanner.tsx
- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
- src/components/ProjectPage/ProjectPage.tsx
- trpc/inferredTypes.ts
- trpc/queries/projectV2.ts
Improve performance for project page
Avoid extra batched requests from client after page's mount
> fix: more queries performance

- src/components/ProjectGoalList/ProjectGoalList.tsx
- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
- trpc/queries/goalV2.ts
- trpc/queries/projectV2.ts
- trpc/router/projectV2.ts
> fix(INTERNAL-1408): fix query for parntership projects

- trpc/router/goal.ts
> fix(ExternalTasks): correct querying criteria and goals for update

- src/middleware.ts
> fix(telemetry): older next support

- cypress/e2e/projects.cy.ts
- src/components/KeyInput/KeyInput.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.tsx
- src/hooks/useProjectResource.ts
- trpc/router/project.ts
- trpc/router/router.i18n/en.json
- trpc/router/router.i18n/ru.json
> real validation for project key

- src/components/GroupedGoalList.tsx
- trpc/inferredTypes.ts
> return project childs

- cypress/fixtures/langs.json
- generated/kysely/types.ts
- prisma/migrations/20241202080534_global_goal_ranks/migration.sql
- prisma/schema.prisma
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/FlatGoalList.tsx
- src/components/GoalTableList/GoalTableList.module.css
- src/components/GoalTableList/GoalTableList.tsx
- src/components/Kanban/Kanban.tsx
- src/components/ProjectGoalList/ProjectGoalList.tsx
- src/components/SortList/SortList.i18n/en.json
- src/components/SortList/SortList.i18n/ru.json
- src/components/SortList/SortList.tsx
- src/schema/common.ts
- src/utils/declareGoalsSsrProps.ts
- src/utils/parseUrlParams.ts
- src/utils/ranking.ts
- trpc/queries/activity.ts
- trpc/queries/goalV2.ts
- trpc/queries/goals.ts
- trpc/queries/ranking.ts
- trpc/router/goalV2.ts
- trpc/router/projectV2.ts
> Goal table ranking

- trpc/queries/ranking.ts
Related discussion in postgres mailing list https://www.postgresql.org/message-id/16958-963f638020de271c%40postgresql.org
> Fix on conflict clause in goal rank update

- package-lock.json
- package.json
Added couple of events for goal/criteria/deps/participants/project manipulation methods
> Update `@taskany/bricks` version

- prisma/seed.ts
- src/utils/worker/create.ts
- src/utils/worker/externalTasksJob.ts
- src/utils/worker/resolve.ts
> refactor(scheduledExternalTasks): implements queue for update

- src/components/ProjectCreateForm/ProjectCreateForm.tsx
> fix(INTERNAL-1572): show errors if exists

- .github/workflows/e2e.yml
> Fix: e2e pipeline

- src/components/Dropdown/Dropdow.module.css
- src/components/Dropdown/Dropdown.tsx
- src/components/FiltersPanel/FiltersPanel.tsx
- src/components/GlobalSearch/GlobalSearch.tsx
- src/components/GoalForm/GoalForm.module.css
- src/components/GoalForm/GoalForm.tsx
- src/components/ProjectCreateForm/ProjectCreateForm.module.css
- src/components/UserDropdown/UserDropdown.module.css
- src/components/UserDropdown/UserDropdown.tsx
- src/schema/project.ts
- src/schema/schema.i18n/en.json
- src/schema/schema.i18n/ru.json
> fix(INTERNAL-1574): markup fixes

- src/components/FormControlEditor/FormControlEditor.tsx
> Fix file uploads in comments

- package-lock.json
- package.json
https://github.com/user-attachments/assets/5ba9b04b-d4aa-4995-8d34-00a2aae14eb9
> Fix read only comment mode

- src/middleware.ts
- src/utils/analyticsEvent.ts
- src/utils/db/createComment.ts
- src/utils/db/index.ts
- trpc/router/goal.ts
- trpc/router/project.ts
> fix(INTERNAL-1673): additional event data

- src/pages/goals/[id].tsx
- trpc/router/goal.ts
> redirect from `/goals/{id}` to `/goals/{scopedId}`

- src/components/FocusTracking.tsx
- src/components/Page/Page.tsx
- src/utils/analyticsEvent.ts
> feat(INTERNAL-1699): listen document visibility state

- trpc/queries/history.ts
> chore: support nullish value for history

- src/utils/integration/jira.ts
- trpc/router/goal.ts
> feat(INTERNAL-1346): set response link to jira issue

- package-lock.json
- package.json
- src/components/GoalPreview/GoalPreviewProvider.tsx
- src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
- src/hooks/useClientEvent.ts
- src/utils/analyticsEvent.ts
- src/utils/db/connection/kysely.ts
- trpc/router/goal.ts
- trpc/router/project.ts
- trpc/router/reaction.ts
- trpc/router/search.ts
> fix(INTERNAL-1698): append rest events

- trpc/router/goal.ts
> search goal by passed identifier

- trpc/router/search.ts
> feat(INTERNAL-1741): projects search bug

- src/hooks/useMarkdown.tsx
> feat(INTERNAL-1671): markdown strong tag bug

- cypress/e2e/projects.cy.ts
- src/utils/integration/jira.ts
- src/utils/worker/externalTasksJob.ts
- src/utils/worker/resolve.ts
> fix(INTERNAL-1745): more stability

- package-lock.json
- package.json
- src/utils/worker/index.ts
- src/utils/worker/sentry.ts
> Sentry for worker

- package-lock.json
- src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
> Access users defaults

- src/components/TagDropdown/TagDropdown.tsx
- trpc/queries/goalV2.ts
- trpc/router/tag.ts
> fix(INTERNAL-1728): tag filter fill

- cypress/fixtures/langs.json
- src/components/SortList/SortList.i18n/en.json
- src/components/SortList/SortList.i18n/ru.json
- src/components/SortList/SortList.tsx
- src/schema/common.ts
- src/utils/parseUrlParams.ts
- trpc/queries/goalV2.ts
- trpc/queries/goals.ts
> feat(INTERNAL-1747): estimate sorting

- src/components/PageNavigation/PageNavigation.tsx
- src/schema/project.ts
- src/utils/db/index.ts
- src/utils/declareSsrProps.ts
- trpc/queries/access.ts
- trpc/queries/goalV2.ts
- trpc/queries/goals.ts
- trpc/queries/project.ts
- trpc/queries/projectV2.ts
- trpc/router/goal.ts
- trpc/router/project.ts
- trpc/router/projectV2.ts
- trpc/router/search.ts
> Hide personal goals and private projects

- src/components/GoalsPage/GoalsPage.tsx
- src/components/GroupedGoalList.tsx
- src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
- src/components/TeamGroupedGoalsList/TeamGroupedGoalsList.tsx
- src/pages/team/[externalTeamId].tsx
- trpc/queries/projectV2.ts
- trpc/router/projectV2.ts
> feat(INTERNAL-1159): crew team projects page
