src/components/GoalPreview/GoalPreview.tsx

Resolve #888
* go to dashboard or project page
* select any goal which possible to edit
* open edit dialog
* close dialog
* select any other goal than select previous
* Voila! You didn't see edit dialog again.
https://github.com/taskany-inc/issues/assets/7002692/29ff5001-2da5-4e9c-be2d-a6055616ea7c

GoalPreview: GoalEditModal reopens automatically

---

prisma/migrations/20230602095919_/migration.sql
prisma/schema.prisma
trpc/router/goal.ts
trpc/router/project.ts

Change field name from `createadAt` to `createdAt`
Related issues #985 
Migration will applied correctly

Upsert estimate field instead of create and create history record about estimate field's change

---

src/components/CriteriaForm/CriteriaForm.tsx

Now weight input haven't native autocomplete
Resolve #1222

Disable completion in criteria weight field

---

src/hooks/useCommentResource.ts
src/schema/goal.ts
trpc/router/goal.ts

Incudes bug fix that throws while updating goal
Resolve #1279 
Now goal update correctly

Goal update method returned error by update criteria state

---

trpc/router/goal.ts

Now suggestion route returns the correct search results by any query, ex. by scoped goal id (FRTNTD-3) or goal title
Resolve #1293 
**NOTE**: select the goal from suggesstion will be fixed after #1198

fix(GoalSuggest): search query params

---

prisma/migrations/20230714171654_/migration.sql
prisma/migrations/20230714181336_/migration.sql
prisma/migrations/20230717183439_/migration.sql
prisma/schema.prisma
prisma/seed.ts
trpc/queries/goals.ts
trpc/router/goal.ts

fix priority sorting: now sorts alphabetically

---

src/components/GoalCreateForm/GoalCreateForm.tsx

Resolve #1230 
Related issues #1326 
request response status 500
https://github.com/taskany-inc/issues/assets/95316053/8a28ed5b-24af-4c37-bd4e-a041e30b1822
request response status 200
https://github.com/taskany-inc/issues/assets/95316053/76c9c360-bbef-4f37-8a0e-5fb728e2cc13
I couldnt find a solution with a utility function because the whole solution comes down to await

Goal create form stays busy after an error backend response

---

src/utils/db.ts
trpc/router/goal.ts

Now after moving goal into archive the average score will recalculate for non-archived goals
Resolve #1370
1. Create goal and criteria
2. Mark criteria as complete
3. Remove goal from the project

The average project score doesn't recalculate after moving goal into an archive

---

src/components/EstimateComboBox.tsx
src/components/TagComboBox.tsx

Resolve #1379 
https://github.com/taskany-inc/issues/assets/95316053/49c79e76-9e9d-4e64-bef9-d5eda47a22a9

Estimate and tag on goal creation form don't close

---

src/components/CriteriaForm/CriteriaForm.tsx
src/components/GoalCriteria/GoalCriteria.tsx

Now `weight` field validation works correctly
Passed value will be checks by validation function
If value is empty then validating process doesn't runs
Resolve #1437 
1. Open add or edit criteria
2. Try to pass value into `weight` filed
1. if value less or greater of available weights interval then behind of the input shows error message
2. By clear value in an input validating message will be dismiss

Broken weight field validation in CriteriaForm

---

Dockerfile
src/utils/worker/mail/templates.ts

Put back worker path + removed type import that broke the worker assembly
- [ x] Bug Fix
Resolve #1449

Worker is not found on docker start

---

prisma/migrations/20230807192046_change_default_timestamps/migration.sql
prisma/schema.prisma

Use utc-based default timestamps as db stores timestamps without time zone
Resolve #1467

default(now) in prisma timestamps looses time zone if it's not UTC

---

src/components/ProjectListItemConnected.tsx

Subprojects count doesn't shown before open Collapsed item

---

package-lock.json
package.json
src/pages/api/upload.ts

Correct attaches sending according to updated useUpload in bricks

---

package-lock.json
package.json
src/components/UserGroup.tsx

Use UserGroup from bricks

---

src/utils/db.ts
trpc/queries/goals.ts
trpc/router/goal.ts
trpc/router/project.ts
trpc/router/search.ts

Resolve #1489
- set role ADMIN via prisma studio
- check how you can change the world

Support ADMIN role

---

src/utils/auth.ts
trpc/router/project.ts

Resolve #1570
Moved the query out of the scope so goal filtering doesn't affect projects. Also changed default keycloak algo to match current standards.

Projects page doesn't show projects with multiple children

---

src/components/DashboardPage/DashboardPage.tsx
src/components/FlatGoalList.tsx
src/components/GoalActivityFeed.tsx
src/components/GoalEditForm/GoalEditForm.tsx
src/components/GoalHeader.tsx
src/components/GoalPage/GoalPage.tsx
src/components/GoalPreview/GoalPreview.tsx
src/components/GoalPreview/GoalPreviewProvider.tsx
src/components/GoalSidebar/GoalSidebar.tsx
src/components/GroupedGoalList.tsx
src/components/ProjectListItemConnected.tsx
src/components/ProjectPage/ProjectPage.tsx
src/hooks/useGoalResource.ts
src/utils/dispatchModal.ts

Based on native events which dispatching from GoalPreview components through useGoalPreview hook.
I'm not sure about event names for this feature `on:goal:update | on:goal:delete`
Example
```ts
const { on } = useGoalPreview();
useEffect(() => {
const unsub = on('on:goal:update', () => {
// any logic after update goal in preview
})
return () => unsub();
}, [on, ...])
```
Resolve #1812 
https://github.com/taskany-inc/issues/assets/7002692/3fc4a218-605d-4cc4-9306-7c6aac241915

Dashboard not updates after goal update

---

src/components/GoalsPage/GoalsPage.tsx
src/hooks/useFiltersPreset.ts
src/hooks/useUrlFilterParams.ts

Resolve #1881 
Filter preset with groupBy param
Same Filter preset with additional ungroup param. Click by `Ungroup` is append query param `groupBy=none` which overriding contains params value in preset
Preset without groupping
Preset without groupping with overriding query param
Any custom filter params with groupping param

Enable Group/Ungroup control

---

src/components/CollapsableItem.tsx
src/components/ProjectListItemConnected.tsx

Fix blinking `Create goal` control by open collapse element
Resolve #1886

The chaos of loading goals in grouped view on /goals page

---

src/components/GroupedGoalList.tsx
src/components/ProjectPage/ProjectPage.tsx

In GoalsPage `cmd+click` is works again
In ProjectPage don't need this behavior for first-level project
Resolve #1907

First level projects are not clickable by cmd+click

---

prisma/migrations/20240131191725_/migration.sql
prisma/schema.prisma

Resolve #2241 
> [!WARNING]
> Duplicate reactions must be removed to avoid problems.
```sql
SELECT emoji, "commentId", "activityId", COUNT(*)
FROM "Reaction"
GROUP BY emoji, "commentId", "activityId"
HAVING COUNT(*) > 1;
```
```sql
SELECT id
FROM (
SELECT
id,
ROW_NUMBER() OVER (PARTITION BY emoji, "commentId", "activityId" ORDER BY id) as row_num
FROM "Reaction"
) AS duplicates
WHERE row_num > 1
```
```sql
DELETE FROM "Reaction"
WHERE id IN (
SELECT id
FROM (
SELECT
id,
ROW_NUMBER() OVER (PARTITION BY emoji, "commentId", "activityId" ORDER BY id) as row_num
FROM "Reaction"
) AS duplicates
WHERE row_num > 1
);
```

Reactions should be unique

---

.eslintrc.js

All count of files which use `import * from '@prisma/client'` is 38 files
```
cypress/plugins/db.ts
src/hooks/useGoalResource.ts
src/hooks/useUrlFilterParams.ts
src/schema/common.ts
src/schema/filter.ts
src/schema/goal.ts
src/types/date.ts
src/types/history.ts
src/utils/auth.ts
src/utils/prisma.ts
src/utils/recalculateCriteriaScore.ts
src/utils/db/calculatedGoalsFields.ts
src/utils/db/createComment.ts
src/utils/db/index.ts
src/utils/worker/goalPingJob.ts
src/utils/worker/index.ts
trpc/queries/access.ts
trpc/queries/goals.ts
trpc/queries/project.ts
trpc/router/goal.ts
trpc/router/project.ts
trpc/router/tag.ts
trpc/router/user.ts
src/components/FlowComboBox.tsx
src/components/GoalCommentCreateForm.tsx
src/components/GoalDependencyList.tsx
src/components/GoalList.tsx …
```

Restrict imports from prisma and trpc in client code

---

src/components/NewGoalCriteria/NewGoalCriteria.tsx

The `defaultChecked` prop is only used during initial render
Resolve #2381

Radio button should be checked when criteria is done

---

src/components/DashboardPage/DashboardPage.tsx
src/components/FlatGoalList.tsx
src/components/GoalTableList/GoalTableList.tsx
src/components/GroupedGoalList.tsx
src/components/ProjectListItemConnected.tsx
src/components/ProjectPage/ProjectPage.tsx

Now the comparison will be performed by selecteted `_shortId` before receiving the goal object in the context of the preview
Drop extra `selectGoalResolver` move marking logic inside `<GoalTableList />` component
Also move preview click handler inside `<GoalTableList /> component
Resolve #2316 
https://github.com/taskany-inc/issues/assets/7002692/a67bbb52-f614-4369-8c34-65b8c4193bcf
Example with network throttling (fast 3G)

Goal selection waits for the preview to load

---

src/components/GoalTableList/GoalTableList.tsx

Remove underline from links in goal table list

---

src/components/GoalCreateForm/GoalCreateForm.tsx
src/components/Page/Page.tsx
src/hooks/useWillUnmount.ts

Fixed sorting by last usage project
Added clear current project from LS by unload event if user close tab the project's page
Also added clear current project on any page exclude project's page
Resolve #2507

Create one more goal resets options

---

generated/kysely/types.ts
prisma/migrations/20240611095016_/migration.sql
prisma/schema.prisma
src/components/UserSettingsPage/UserSettingsPage.i18n/en.json
src/components/UserSettingsPage/UserSettingsPage.i18n/ru.json
src/components/UserSettingsPage/UserSettingsPage.tsx
src/schema/user.ts
src/utils/db/createComment.ts
src/utils/prepareRecipients.ts
src/utils/worker/mail/templates.ts
trpc/router/goal.ts
trpc/router/project.ts

Added a new column in settings' model
By prepare recipient list will get setting by each recipient user and filtering by settings' field
Also add link to settings' user page in emails
Resolve #2584

Disable email notifications option

---

src/components/DashboardPage/DashboardPage.tsx
trpc/queries/projectV2.ts
trpc/router/projectV2.ts

Fix goals counter in Dashboard
Now, overall goals count increasing by load next page of Dashboard including showed goals by applying filters
Resolve #2745 
Related issues #2653

Fix calculate goals count in Dashboard page

---

trpc/queries/projectV2.ts

Filter by strict date doesn't works in Dashboard

---

src/components/GoalBadge.tsx
src/components/GoalCriteria/GoalCriteria.module.css
src/components/GoalCriteria/GoalCriteria.tsx
src/components/GoalTableList/GoalTableList.tsx
src/components/IssueStats/IssueStats.tsx
src/utils/recalculateCriteriaScore.ts
trpc/queries/criteria.ts
trpc/router/goal.ts

In a goal user can see linked goal scoring if it has any criteria
Also added accounting of partial score from linked goal by criterion
Resolve #2778 
Related issues https://github.com/taskany-inc/bricks/issues/1137

Support partial goal progress in criteria

---

src/components/GoalActivityFeed/GoalActivityFeed.tsx
src/components/GoalCriteriaSuggest.tsx
src/schema/common.ts
trpc/queries/goalV2.ts
trpc/router/goal.ts
trpc/router/goalV2.ts
trpc/router/index.ts
trpc/router/router.i18n/en.json
trpc/router/router.i18n/ru.json

Goal cannot be it's own criteria

---

cypress/e2e/projects.cy.ts
src/components/DashboardPage/DashboardPage.tsx
src/components/ExploreProjectsPage/ExploreProjectsPage.tsx
src/components/ExploreProjectsStarredPage/ExploreProjectsStarredPage.tsx
src/components/ExploreTopProjectsPage/ExploreTopProjectsPage.tsx
src/components/ProjectListItem/ProjectListItem.tsx
src/components/ProjectListItemCollapsable/ProjectListItemCollapsable.tsx
src/components/ProjectListItemConnected/ProjectListItemConnected.tsx
src/components/ProjectSubscriptionButtons/ProjectSubscriptionButtons.module.css
src/components/ProjectSubscriptionButtons/ProjectSubscriptionButtons.tsx

DOM nesting validation

---

cypress/e2e/dashboard.cy.ts
src/components/DashboardPage/DashboardPage.tsx
src/components/FiltersBar/FiltersBar.tsx
src/components/FiltersPanel/FiltersPanel.i18n/en.json
src/components/FiltersPanel/FiltersPanel.i18n/ru.json
src/components/FiltersPanel/FiltersPanel.tsx
src/hooks/useUrlFilterParams.ts
src/schema/common.ts
src/utils/domObjects.ts
trpc/queries/goalV2.ts
trpc/queries/projectV2.ts

Add view option - show empty projects

---

src/components/CriteriaForm/CriteriaForm.tsx
src/components/GoalActivityFeed/GoalActivityFeed.tsx
src/components/GoalCriteriaSuggest.tsx
src/components/Page/Page.tsx
src/utils/declareSsrProps.ts
src/utils/integration/jira.ts
src/utils/pageContext.ts
trpc/router/jira.ts

Resolve #2964 
Related issues #2484 , #2955

Don't destroy service on startup if jira env variable is undefined

---

src/components/CriteriaForm/CriteriaForm.i18n/en.json
src/components/CriteriaForm/CriteriaForm.i18n/ru.json
src/components/CriteriaForm/CriteriaForm.tsx
src/components/HistoryRecord/HistoryRecord.i18n/ru.json
src/components/HistoryRecord/HistoryRecord.tsx
src/utils/db/calculatedGoalsFields.ts
src/utils/integration/jira.ts
trpc/queries/history.ts
trpc/router/goal.ts

Also failed tasks marks linked criteria as done, but does not affect on completed goal score 
Resolve #2989

Change colors for task status badge

---

prisma/seed.ts
src/utils/recalculateCriteriaScore.ts
src/utils/worker/create.ts
src/utils/worker/externalTasksJob.ts
src/utils/worker/index.ts
src/utils/worker/resolve.ts
src/utils/worker/utils.ts
trpc/router/goal.ts

Create a scheduled task to update jira ticket status into criteria progres

---

src/components/ProjectAccessUser/ProjectAccessUser.tsx
src/components/ProjectContext/ProjectContext.tsx
src/components/ProjectListItem/ProjectListItem.tsx
src/components/ProjectPage/ProjectPage.tsx
src/components/ProjectParticipants/ProjectParticipants.tsx
src/components/ProjectSettingsPage/ProjectSettingsPage.tsx
src/components/ProjectTeamPage/ProjectTeamPage.tsx
src/components/TeamComboBox/TeamComboBox.tsx
src/components/UserEditableList/UserEditableList.tsx
src/hooks/useProjectResource.ts
src/pages/projects/[id]/index.tsx
src/pages/projects/[id]/settings.tsx
src/pages/projects/[id]/team.tsx
src/schema/project.ts
src/utils/recalculateCriteriaScore.ts
trpc/inferredTypes.ts
trpc/queries/activity.ts
trpc/queries/goalV2.ts
trpc/queries/projectV2.ts
trpc/router/projectV2.ts

Refactor project's query
Replaced prisma queries with the kysely queries on project's goals, teams and settings pages
Fix calculate the partial criteria goal score

Fix partial criteria score

---

cypress/e2e/dashboard.cy.ts
cypress/index.d.ts
cypress/support/index.ts
trpc/queries/goalV2.ts
trpc/queries/projectV2.ts
trpc/router/projectV2.ts
trpc/utils.ts

read rules for each personalized dashboard project

---

src/utils/anyEntityCheck.ts
trpc/queries/project.ts

fix(ProjectAccess): correct access check

---

src/components/ExplorePageHeader/ExplorePageHeader.tsx
src/components/ExploreProjectsPage/ExploreProjectsPage.tsx
src/pages/explore/projects/index.tsx
trpc/router/project.ts

Changed route handler for getting projects list
Added `Loading` status while querying next page of projects

fix(INTERNAL-1530): `/explore/projects` pagination

---

generated/kysely/types.ts
package-lock.json
prisma/migrations/20250226082910_fitlers_target/migration.sql
prisma/schema.prisma
src/components/DashboardPage/DashboardPage.tsx
src/components/FilterCreateForm/FilterCreateForm.tsx
src/components/GoalsPage/GoalsPage.tsx
src/components/PageNavigation/PageNavigation.tsx
src/hooks/router.ts
src/hooks/useFiltersPreset.ts
src/schema/filter.ts
src/utils/getPageTitle.ts
trpc/queries/projectV2.ts

https://github.com/user-attachments/assets/8cca7805-53c6-4c20-9511-52c25dfd80c3

Support preset target
